# Generated by Django 5.2.4 on 2025-08-21 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.city",
                verbose_name="Service city",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="languages",
            field=models.ManyToManyField(
                blank=True, to="common.language", verbose_name="Languages spoken"
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="service_types",
            field=models.ManyToManyField(
                blank=True,
                to="common.servicetype",
                verbose_name="Service types offered",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.customerprofile",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.customerprofile",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="verificationdocument",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.customerprofile",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="verificationdocument",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["city", "is_available"], name="profiles_cu_city_id_051075_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["average_rating"], name="profiles_cu_average_4b88b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="availability",
            index=models.Index(
                fields=["customer", "date", "is_available"],
                name="profiles_av_custome_d6d4fc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together={("customer", "date")},
        ),
    ]
