# Generated by Django 5.2.4 on 2025-08-04 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.city",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="guide",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guidelanguage",
            name="guide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guide_languages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guidelanguage",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.language"
            ),
        ),
        migrations.AddField(
            model_name="guideprofile",
            name="languages",
            field=models.ManyToManyField(blank=True, to="profiles.guidelanguage"),
        ),
        migrations.AddField(
            model_name="guideprofile",
            name="operating_cities",
            field=models.ManyToManyField(blank=True, to="common.city"),
        ),
        migrations.AddField(
            model_name="guideprofile",
            name="services",
            field=models.ManyToManyField(blank=True, to="common.service"),
        ),
        migrations.AddField(
            model_name="guideprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guide_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="guide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "city"), ("user", "guide")},
        ),
        migrations.AlterUniqueTogether(
            name="guidelanguage",
            unique_together={("guide", "language")},
        ),
        migrations.AddIndex(
            model_name="guideprofile",
            index=models.Index(
                fields=["is_verified"], name="guide_profi_is_veri_c48d63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guideprofile",
            index=models.Index(
                fields=["is_available"], name="guide_profi_is_avai_a2e5c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guideprofile",
            index=models.Index(
                fields=["average_rating"], name="guide_profi_average_0b28a3_idx"
            ),
        ),
    ]
