# Generated by Django 5.2.4 on 2025-09-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/img.png",
                null=True,
                upload_to="avatars/",
                verbose_name="Profile picture",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/img.png",
                null=True,
                upload_to="avatars/",
                verbose_name="Profile picture",
            ),
        ),
    ]
