# Generated by Django 5.2.4 on 2025-08-10 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_city_unique_together_alter_country_code_and_more"),
        ("profiles", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="availability",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.customerprofile",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="availability",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="availability",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="availability",
            name="note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="availability",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="languages",
            field=models.ManyToManyField(
                blank=True, to="common.language", verbose_name="Languages spoken"
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="common.city",
                verbose_name="Service city",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="languages",
            field=models.ManyToManyField(
                blank=True, to="common.language", verbose_name="Languages spoken"
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="professional_bio",
            field=models.TextField(verbose_name="Professional biography"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="service_areas",
            field=models.TextField(blank=True, verbose_name="Service areas"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="service_types",
            field=models.ManyToManyField(
                to="common.servicetype", verbose_name="Service types offered"
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.customerprofile",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.customerprofile",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("id_card", "ID Card"),
                    ("passport", "Passport"),
                    ("license", "Professional License"),
                    ("certificate", "Certificate"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="file",
            field=models.FileField(upload_to="verification/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
