# Generated by Django 5.2.4 on 2025-10-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_clientprofile_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio/%Y/%m/",
                verbose_name="Image",
            ),
        ),
    ]
