# Generated by Django 5.2.4 on 2025-08-17 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_city_unique_together_alter_country_code_and_more"),
        ("profiles", "0004_clientprofile_country_clientprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.city",
                verbose_name="Service city",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="professional_bio",
            field=models.TextField(
                blank=True, null=True, verbose_name="Professional biography"
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="service_areas",
            field=models.TextField(blank=True, null=True, verbose_name="Service areas"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="service_types",
            field=models.ManyToManyField(
                blank=True,
                to="common.servicetype",
                verbose_name="Service types offered",
            ),
        ),
    ]
