# Generated by Django 5.2.4 on 2025-08-17 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_city_unique_together_alter_country_code_and_more"),
        ("profiles", "0005_alter_customerprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprofile",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.country",
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.country",
                verbose_name="Country",
            ),
        ),
    ]
