# Generated by Django 5.2.4 on 2025-08-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_clientprofile_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="professional_bio",
            field=models.TextField(
                blank=True, default="", verbose_name="Professional biography"
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="service_areas",
            field=models.TextField(
                blank=True, default="", verbose_name="Service areas"
            ),
        ),
    ]
