# Generated by Django 5.2.4 on 2025-08-04 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loginsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresetattempt",
            index=models.Index(
                fields=["email", "created_at"], name="password_re_email_b3a644_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresetattempt",
            index=models.Index(
                fields=["ip_address", "created_at"],
                name="password_re_ip_addr_0dc177_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(
                fields=["email", "code_type"], name="verificatio_email_1ddc9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(fields=["code"], name="verificatio_code_8f9b5b_idx"),
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(
                fields=["expires_at"], name="verificatio_expires_bef114_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginsession",
            index=models.Index(
                fields=["user", "is_active"], name="login_sessi_user_id_f258eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginsession",
            index=models.Index(
                fields=["session_key"], name="login_sessi_session_9d336d_idx"
            ),
        ),
    ]
