# Generated by Django 5.2.4 on 2025-07-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emailverification_is_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="code",
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
