# Generated by Django 5.2.4 on 2025-07-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_emailverification_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("chat_id", models.BigIntegerField()),
                ("code", models.CharField(db_index=True, max_length=6)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-expires_at",),
                "unique_together": {("phone", "code")},
            },
        ),
    ]
