import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(undefined);

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

const translations = {
    en: {
        // Navigation
        'nav.findGuides': 'Find Guides',
        'nav.becomeGuide': 'Become a Guide',
        'nav.signIn': 'Sign In',
        'nav.messages': 'Messages',
        'nav.dashboard': 'Dashboard',
        'nav.logout': 'Logout',
        'nav.searchPlaceholder': 'Search where to go',

        'landing.hero.title': 'Connect with Local',
        'landing.hero.subtitle': 'Expert Guides',
        'landing.hero.description': 'Discover authentic experiences with verified local guides worldwide',
        'landing.hero.whereTo': 'Where do you want to go?',
        'landing.hero.selectService': 'Select Service',
        'landing.hero.searchGuides': 'Search Guides',
        'landing.hero.verifiedGuides': 'Verified Guides',
        'landing.hero.countries': 'Countries',
        'landing.hero.averageRating': 'Average Rating',
        'landing.topGuides.title': 'Top Rated Guides',
        'landing.topGuides.description': 'Meet our most experienced and highly rated local experts',
        'landing.services.title': 'Popular Services',
        'landing.services.description': 'Explore the most requested services from our community',
        'landing.cities.title': 'Featured Destinations',
        'landing.cities.description': 'Discover amazing experiences in these popular cities',
        'landing.features.title': 'Why Choose UzGuide?',
        'landing.features.description': 'Experience the difference of authentic local expertise',
        'landing.features.verified': 'Verified Guides',
        'landing.features.verifiedDesc': 'All our guides are background-checked and verified for your safety',
        'landing.features.support': '24/7 Support',
        'landing.features.supportDesc': 'Round-the-clock customer support for seamless travel experiences',
        'landing.features.global': 'Global Coverage',
        'landing.features.globalDesc': 'Connect with local experts in over 150+ destinations worldwide',
        'landing.cta.title': 'Ready to Start Your Journey?',
        'landing.cta.description': 'Join thousands of travelers who have discovered authentic experiences with local guides',
        'landing.cta.findGuide': 'Find Your Guide',
        'landing.cta.becomeGuide': 'Become a Guide',

        // Qo‘shimcha umumiy kalitlar (Navbar/CTAlarda kerak bo‘lishi mumkin)
        'landing.topGuides.empty': 'No guides yet',

        // Services
        'service.tourGuide': 'Tour Guide',
        'service.translator': 'Translator',
        'service.photographer': 'Photographer',
        'service.driver': 'Driver/Taxi',
        'service.shoppingHelper': 'Shopping Helper',
        'service.foodGuide': 'Food Guide',
        'service.businessFixer': 'Business Fixer',
        'service.culturalExpert': 'Cultural Expert',
        'service.localExpert': 'Local Expert',
        'service.interpreter': 'Interpreter',
        'service.eventPlanner': 'Event Planner',
        'service.airportTransfer': 'Airport Transfer',
        'service.groupTours': 'Group Tours',

        // Search Page
        'search.title': 'Find Your Perfect Guide',
        'search.placeholder': 'Search by location, service, or guide name...',
        'search.filters': 'Filters',
        'search.serviceType': 'Service Type',
        'search.allServices': 'All Services',
        'search.priceRange': 'Price Range ($/hour)',
        'search.minRating': 'Minimum Rating',
        'search.availability': 'Availability',
        'search.availableNow': 'Available Now',
        'search.availableToday': 'Available Today',
        'search.availableWeek': 'Available This Week',
        'search.languages': 'Languages',
        'search.anyLanguage': 'Any Language',
        'search.guidesFound': 'guides found',
        'search.sortBy': 'Sort by Relevance',
        'search.sortPrice': 'Price: Low to High',
        'search.sortPriceDesc': 'Price: High to Low',
        'search.sortRating': 'Rating: High to Low',
        'search.sortReviews': 'Most Reviews',
        'search.verified': 'Verified',
        'search.viewProfile': 'View Profile',
        'search.bookNow': 'Book Now',
        'search.speaks': 'Speaks',
        'search.responds': 'Typically responds',

        // Guide Dashboard
      "guide.dashboard.title": "Mening Boshqaruv Panelim",
      "guide.dashboard.description": "Rezervatsiyalaringizni, xizmatlaringizni va tajribalaringizni boshqaring",
      "guide.dashboard.bookings": "Rezervatsiyalar",
      "guide.dashboard.earnings": "Daromadlar",
      "guide.dashboard.reviews": "Sharhlar",
      "guide.dashboard.settings": "Sozlamalar",
      "guide.dashboard.activeBookings": "Faol Rezervatsiyalar",
      "guide.dashboard.averageRating": "O'rtacha Baho",
      "guide.dashboard.responseRate": "Javob Berish Foizi",
      "guide.dashboard.saveChanges": "O'zgarishlarni Saqlash",
      "guide.dashboard.changeProfilePicture": "Profil Rasmini O'zgartirish",
      "guide.dashboard.uploadNewPhoto": "Yangi Rasm Yuklash",
      "guide.dashboard.removePhoto": "Rasmni O'chirish",
      "guide.dashboard.photoRequirements": "Rasm hajmi 5MB dan oshmasligi kerak, faqat JPEG, PNG yoki GIF formatlari qabul qilinadi",
      "guide.dashboard.saved": "Profil ma'lumotlari muvaffaqiyatli saqlandi",
      "guide.dashboard.saveFailed": "Profil ma'lumotlarini saqlashda xatolik yuz berdi",
      "guide.dashboard.services": "Xizmatlar",
      "guide.dashboard.addService": "Yangi Xizmat Qo'shish",
      "guide.dashboard.cancel": "Bekor Qilish",
      "guide.dashboard.saveService": "Xizmatni Saqlash",
      "guide.dashboard.deleteService": "Xizmatni O'chirish",
      "guide.dashboard.serviceName": "Xizmat Nomi",


      // Guide Bookings
      "guide.bookings.acceptFailed": "Rezervatsiyani qabul qilishda xatolik yuz berdi",
      "guide.bookings.declineFailed": "Rezervatsiyani rad etishda xatolik yuz berdi",
      "guide.bookings.completeFailed": "Rezervatsiyani tugallandi deb belgilashda xatolik yuz berdi",
      "guide.bookings.bookingsRefreshed": "Rezervatsiyalar muvaffaqiyatli yangilandi",


// Guide Detail
        'guide.detail.notFound': 'Guide not found',
        'guide.detail.back': 'Back to search',
        'guide.detail.chatWith': 'Chat with {{name}}',
        'guide.detail.theGuide': 'guide',
        'guide.detail.bookTitle': 'Book this guide',
        'guide.detail.unavailable': 'Currently unavailable',
        'guide.detail.requestBooking': 'Request booking',
        'guide.detail.signInToBook': 'Sign in to book',
        'guide.detail.startDate': 'Start date',
        'guide.detail.endDate': 'End date',
        'guide.detail.check': 'Check Availability',
        'guide.detail.checking': 'Checking...',
        'guide.detail.guests': 'Guests',
        'guide.detail.messageLabel': 'Message to the guide (optional)',
        'guide.detail.messagePh': 'Tell a bit about your plan, preferences, schedule…',
        'guide.detail.preparing': 'Preparing…',
        'guide.detail.submit': 'Submit booking',
        'guide.detail.portfolio': 'Portfolio',
        'guide.detail.noPortfolio': 'No portfolio items',

// Guide Detail alerts / results
        'guide.detail.resolveError': 'Guide profile not resolved yet.',
        'guide.detail.chooseDates': 'Choose start and end dates first.',
        'guide.detail.availableOk': 'Guide is available for these dates.',
        'guide.detail.availableNo': 'Guide is not available for these dates.',
        'guide.detail.availableFail': 'Failed to check availability.',
        'guide.detail.noGuideId': 'Guide ID was not resolved. Refresh page or try again.',
        'guide.detail.selectDates': 'Please select start and end dates',
        'guide.detail.endAfterStart': 'End date must be after start date',
        'guide.detail.notAvailable': 'Guide is not available. Please check availability first.',
        'guide.detail.redirecting': 'Redirecting to booking form…',

        // Booking – new keys
        'booking.errInvalidGuide': 'Invalid guide profile.',
        'booking.errGuideNotFound': 'Guide not found',
        'booking.errChooseDates': 'Choose start and end dates first.',
        'booking.availableOk': 'Available ✅',
        'booking.availableNo': 'Not available',
        'booking.availableFail': 'Failed to check availability',
        'booking.errNoGuide': 'No guide selected.',
        'booking.errSelectDates': 'Please select dates.',
        'booking.errEndBeforeStart': 'End date cannot be earlier than start date.',
        'booking.errCountryRequired': 'Country is required.',
        'booking.creating': 'Creating your booking...',
        'booking.created': 'Booking created! Your guide will contact you shortly.',
        'booking.errCreateFailed': 'Failed to create booking. Please try again.',
        'booking.errOnlyCompletedReview': 'You can only review a completed booking.',
        'booking.errReviewBookingNotFound': 'Booking not found for review.',
        'booking.errSelectRating': 'Please select a rating',
        'booking.reviewSubmitted': 'Review submitted. Thank you!',
        'booking.errSubmitReview': 'Failed to submit review.',
        'booking.serviceSchedule': 'Service & Schedule',
        'booking.selectServiceSchedule': 'Select Service & Schedule',
        'booking.country': 'Country',
        'booking.city': 'City',
        'booking.startDate': 'Start Date',
        'booking.endDate': 'End Date',
        'booking.checkAvailability': 'Check Availability',
        'booking.checking': 'Checking...',
        'booking.checkHint': 'Optional check before you continue',
        'booking.notesLabel': 'Notes for your guide',
        'booking.requestBooking': 'Request Booking',
        'booking.writeReview': 'Write a Review',
        'booking.rating': 'Rating',
        'booking.commentOpt': 'Comment (optional)',
        'booking.shareExperience': 'Share your experience…',
        'booking.sending': 'Sending…',
        'booking.submitReview': 'Submit review',
        'booking.summary': 'Booking Summary',
        'booking.rate': 'Rate',
        'booking.perHour': 'hour',
        'booking.perDay': 'day',

        // Dashboard (mavjud + yangi)
        'dashboard.title': 'My Dashboard',
        'dashboard.description': 'Manage your bookings, guides, and travel experiences',
        'dashboard.upcomingBookings': 'Upcoming Bookings',
        'dashboard.pastBookings': 'Past Bookings',
        'dashboard.total': 'Total',
        'dashboard.status': 'Status',
        'dashboard.upcomingBookingsTitle': 'Upcoming Bookings',
        'dashboard.noUpcoming': 'No upcoming bookings.',
        'dashboard.findGuide': 'Find a Guide',
        'dashboard.planNext': 'and plan your next tour!',
        'dashboard.noPast': 'No past bookings',
        'dashboard.pageXofN': 'Page {x} • Total {n}',
        'dashboard.page': 'Page {x}',
        'dashboard.myBookings': 'My Bookings',
        'dashboard.profileInfo': 'Profile Information',
        'dashboard.refresh': 'Refresh',

// Card actions
        'dashboard.cancel': 'Cancel',
        'dashboard.markComplete': 'Complete',
        'dashboard.leaveReview': 'Leave Review',

// Confirmations / statuses / errors
        'dashboard.confirmCancel': 'Cancel this booking?',
        'dashboard.confirmComplete': 'Mark this booking as complete?',
        'dashboard.statusCancelled': 'Cancelled',
        'dashboard.statusCompleted': 'Completed',
        'dashboard.errCancel': 'Failed to cancel booking',
        'dashboard.errComplete': 'Failed to complete booking',
        'dashboard.errResolveProfile': 'Could not resolve guide profile',
        'dashboard.errResolveReview': 'Could not resolve review target',

// Profile section
        'dashboard.avatarHint': 'JPG, PNG, GIF, WEBP • Max 5MB',
        'dashboard.uploading': 'Uploading...',
        'dashboard.uploadPhoto': 'Upload Photo',
        'dashboard.removePhoto': 'Remove Photo',
        'dashboard.firstName': 'First name',
        'dashboard.lastName': 'Last name',
        'dashboard.emailReadonly': 'Email (readonly)',
        'dashboard.phone': 'Phone',
        'dashboard.saveChanges': 'Save changes',
        'dashboard.saving': 'Saving…',
        'dashboard.saved': 'Profile saved',
        'dashboard.errSave': 'Failed to save profile',
        'dashboard.avatarMax': 'Max 5MB',
        'dashboard.avatarTypes': 'Please select JPG/PNG/GIF/WEBP',
        'dashboard.avatarUpdated': 'Avatar updated',
        'dashboard.errAvatarUpload': 'Avatar upload failed',
        'dashboard.avatarRemoved': 'Avatar removed',
        'dashboard.errAvatarRemove': 'Failed to remove avatar',

// Overlays
        'dashboard.cancelling': 'Cancelling booking…',
        'dashboard.completing': 'Completing booking…',

        // Guide – nav/labels
        'guide.nav.overview': 'Overview',
        'guide.nav.profileServices': 'Profile & Services',
        'guide.nav.analytics': 'Analytics',

        'guide.common.yourName': 'Your Name',
        'guide.common.tourist': 'Tourist',
        'guide.common.guest': 'Guest',
        'guide.common.service': 'Service',
        'guide.common.scheduled': 'scheduled',

// Overview
        'guide.overview.welcome': 'Welcome back, {name}!',
        'guide.overview.todayCount': 'You have {n} tours scheduled for today',
        'guide.overview.yourRating': 'Your Rating',
        'guide.overview.responseRate': 'Response Rate',
        'guide.overview.last30': 'Last 30 days',
        'guide.overview.todaySchedule': "Today's Schedule",
        'guide.overview.noToursToday': 'No tours scheduled for today',

// Bookings
        'guide.bookings.pending': 'Pending Requests',
        'guide.bookings.confirmed': 'Confirmed Bookings',
        'guide.bookings.accept': 'Accept',
        'guide.bookings.decline': 'Decline',
        'guide.bookings.markCompleted': 'Mark Completed',
        'guide.bookings.noPending': 'No pending requests',
        'guide.bookings.noConfirmed': 'No confirmed bookings',
        'guide.bookings.offer': 'Offer',
        'guide.bookings.detailTitle': 'Booking details',
        'guide.bookings.title': 'Title',
        'guide.bookings.status': 'Status',
        'guide.bookings.tourist': 'Tourist',
        'guide.bookings.dates': 'Dates',
        'guide.bookings.location': 'Location',
        'guide.bookings.message': 'Message',
        'guide.bookings.declineTitle': 'Decline request',
        'guide.bookings.reasonOpt': 'Reason (optional)',
        'guide.bookings.reasonPh': 'E.g., Not available on selected dates',
        'guide.dashboard.bookingsRefreshed': 'Bookings refreshed',
        'guide.dashboard.acceptFailed': 'Failed to accept booking',
        'guide.dashboard.declineFailed': 'Failed to decline booking',
        'guide.dashboard.completeFailed': 'Failed to mark as completed',

// Profile
        'guide.dashboard.profileInfo': 'Profile Information',
        'guide.profile.firstName': 'First Name',
        'guide.profile.lastName': 'Last Name',
        'guide.profile.emailReadonly': 'Email (readonly)',
        'guide.profile.location': 'Location (Country name or code)',
        'guide.profile.locationPh': 'e.g. Uzbekistan or UZ',
        'guide.profile.bio': 'Bio',
        'guide.profile.bioPh': 'Tell us about yourself and your experience...',
        'guide.profile.languages': 'Languages (comma separated)',
        'guide.profile.languagesPh': 'e.g. English, Russian, Uzbek',
        'guide.profile.known': 'Known',
        'guide.profile.langsNotLoaded': 'Language catalog not loaded.',
        'guide.profile.years': 'Years of Experience',

// Portfolio/services
        'guide.service.item': 'Item',
        'guide.service.order': 'Order: {n}',
        'guide.service.preview': 'Preview',
        'guide.service.noDesc': 'No description',
        'guide.service.empty': 'No portfolio items',
        'guide.service.titlePh': 'e.g. Old Town Walk',
        'guide.service.descPh': 'Short description…',
        'guide.service.orderLabel': 'Order',
        'guide.service.imageReq': 'Image *',
        'guide.dashboard.portfolioCreated': 'Portfolio item created',
        'guide.dashboard.portfolioCreateFailed': 'Portfolio create failed',
        'guide.dashboard.confirmDelete': 'Delete this item?',
        'guide.dashboard.deleteFailed': 'Delete failed',
        'guide.dashboard.portfolioMax': 'Max 10MB',
        'guide.dashboard.photoRequired': 'Image is required',

// Photo / avatar
        'guide.dashboard.photoMax': 'Max 5MB',
        'guide.dashboard.photoTypes': 'Please select JPG/PNG/GIF',
        'guide.dashboard.photoUpdated': 'Avatar updated',
        'guide.dashboard.photoUploadFailed': 'Avatar upload failed',
        'guide.dashboard.photoRemoved': 'Avatar removed',
        'guide.dashboard.photoRemoveFailed': 'Failed to remove avatar',

// Earnings
        'guide.earn.thisMonth': 'This Month',
        'guide.earn.thisMonthShort': 'This month',
        'guide.earn.totalBalance': 'Total Balance',
        'guide.earn.monthly': 'Monthly Earnings',
        'guide.earn.average': 'Average',
        'guide.earn.perBooking': 'Per Booking',
        'guide.earn.pendingShort': 'Pending',
        'guide.earn.available': 'Available',
        'guide.earn.transactions': 'Transaction History',
        'guide.earn.export': 'Export',
        'guide.earn.date': 'Date',
        'guide.earn.tourist': 'Tourist',
        'guide.earn.service': 'Service',
        'guide.earn.amount': 'Amount',
        'guide.earn.status': 'Status',
        'guide.earn.noTx': 'No transactions',
        'guide.earn.withdraw': 'Withdraw ${amount}',

// Reviews
        'guide.reviews.count': 'reviews',
        'guide.reviews.none': 'No reviews yet',

        // Guide List (search)
          "guide.list.title": "Find Guides",
          "guide.list.apply": "Apply Filters",
          "guide.list.placeholder": "Search by name or surname...",
          "guide.list.allCountries": "All Countries",
          "guide.list.anyRating": "Any Rating",
          "guide.list.search": "Search",
          "guide.list.clear": "Clear Filters",
          "guide.list.error": "Error loading guides",
          "guide.list.empty": "No guides found",
          "guide.list.experience": "Experience",
          "guide.list.years": "Years",
          "guide.list.viewProfile": "View Profile",
          "guide.list.prev": "Previous",
          "guide.list.next": "Next",
          "guide.list.page": "Page",
          "guide.list.of": "of",

// Stats / analytics
        'guide.stats.week': 'Bookings This Week',
        'guide.stats.month': 'Bookings This Month',
        'guide.stats.completion': 'Completion Rate',
        'guide.stats.response': 'Response Rate',
        'guide.stats.popular': 'Most Popular Services',
        'guide.stats.noData': 'No data',
        'guide.stats.monthlyPerf': 'Monthly Performance',
        'guide.stats.chartPlaceholder': 'Performance analytics chart',

// Common guide extras
        'guide.common.guestPlural': 'guests',

        // Chat (new/completed)
        'chat.title': 'Messages',
        'chat.description': 'Your conversations with guides and tourists',
        'chat.searchConversations': 'Search conversations...',
        'chat.onlineNow': 'Online now',
        'chat.lastSeen': 'Last seen',
        'chat.bookingDetails': 'Booking Details',
        'chat.typeMessage': 'Type your message…',
        'chat.aiTranslation': 'AI translation available for multi-language conversations',
        'chat.photo': 'Photo',

        'chat.user': 'User',
        'chat.me': 'Me',
        'chat.errLoadMessages': 'Failed to load messages',
        'chat.errSend': 'Failed to send message',
        'chat.noConversations': 'No conversations',
        'chat.loadOlder': 'Load older messages',
        'chat.selectConversation': 'Select a conversation',
        'chat.more': 'More options',
        'chat.back': 'Back',
        'chat.send': 'Send',
        'chat.emojis': 'Emojis',
        'chat.insertEmoji': 'Insert emoji',
        'chat.rtcEnabled': 'Real-time chat is enabled.',

        // Auth
        'auth.welcomeBack': 'Welcome back',
        'auth.createAccount': 'Create your account',
        'auth.signInDescription': 'Sign in to your account to continue',
        'auth.signUpDescription': 'Join thousands of travelers and guides worldwide',
        'auth.joinAs': 'I want to join as a:',
        'auth.tourist': 'Tourist',
        'auth.touristDesc': 'Find and book local guides',
        'auth.guide': 'Guide',
        'auth.guideDesc': 'Offer your local expertise',
        'auth.fullName': 'Full Name',
        'auth.emailAddress': 'Email Address',
        'auth.yourLocation': 'Your Location',
        'auth.password': 'Password',
        'auth.confirmPassword': 'Confirm Password',
        'auth.agreeTerms': 'I agree to the',
        'auth.termsOfService': 'Terms of Service',
        'auth.privacyPolicy': 'Privacy Policy',
        'auth.signIn': 'Sign In',
        // 'auth.createAccount': 'Create Account',
        'auth.noAccount': "Don't have an account?",
        'auth.haveAccount': 'Already have an account?',
        'auth.signUp': 'Sign up',
        'auth.continueWith': 'Or continue with',
        'auth.google': 'Google',
        'auth.facebook': 'Facebook',
        'auth.trustedBy': 'Trusted by thousands of travelers worldwide',
        'auth.secureVerified': 'Secure & Verified',
        'auth.safe': '100% Safe',

        // Footer
        'footer.description': 'Connect with verified local guides worldwide. Discover authentic experiences and create unforgettable memories.',
        'footer.quickLinks': 'Quick Links',
        'footer.findGuides': 'Find Guides',
        'footer.becomeGuide': 'Become a Guide',
        'footer.aboutUs': 'About Us',
        'footer.howItWorks': 'How It Works',
        'footer.safety': 'Safety',
        'footer.support': 'Support',
        'footer.helpCenter': 'Help Center',
        'footer.contactUs': 'Contact Us',
        'footer.termsOfService': 'Terms of Service',
        'footer.privacyPolicy': 'Privacy Policy',
        'footer.cancellationPolicy': 'Cancellation Policy',
        'footer.contact': 'Contact',
        'footer.newsletter': 'Newsletter',
        'footer.yourEmail': 'Your email',
        'footer.subscribe': 'Subscribe',
        'footer.allRightsReserved': 'All rights reserved.',
        'footer.sitemap': 'Sitemap',
        'footer.accessibility': 'Accessibility',
        'footer.cookiePolicy': 'Cookie Policy',

        // Common
        'common.loading': 'Loading...',
        'common.error': 'Error',
        'common.success': 'Success',
        'common.cancel': 'Cancel',
        'common.save': 'Save',
        'common.edit': 'Edit',
        'common.delete': 'Delete',
        'common.view': 'View',
        'common.close': 'Close',
        'common.next': 'Next',
        'common.previous': 'Previous',
        'common.search': 'Search',
        'common.filter': 'Filter',
        'common.sort': 'Sort',
        'common.date': 'Date',
        'common.time': 'Time',
        'common.location': 'Location',
        'common.price': 'Price',
        'common.rating': 'Rating',
        'common.reviews': 'Reviews',
        'common.hour': 'hour',
        'common.hours': 'hours',
        'common.min': 'Min',
        'common.max': 'Max',
        'common.all': 'All',
        'common.none': 'None',
        'common.yes': 'Yes',
        'common.no': 'No',
        'common.ok': 'OK',
    },
    uz: {
        // Navigation
        'nav.findGuides': 'Gidlarni topish',
        'nav.becomeGuide': 'Gid bo\'lish',
        'nav.signIn': 'Kirish',
        'nav.messages': 'Xabarlar',
        'nav.dashboard': 'Boshqaruv paneli',
        'nav.logout': 'Chiqish',
        'nav.searchPlaceholder': 'Qayerga bormoqchisiz?',

        // Landing Page
        'landing.hero.title': 'Mahalliy bilan bog\'laning',
        'landing.hero.subtitle': 'Mutaxassis gidlar',
        'landing.hero.description': 'Butun dunyo bo\'ylab tasdiqlangan mahalliy gidlar bilan haqiqiy tajribalarni kashf eting',
        'landing.hero.whereTo': 'Qayerga bormoqchisiz?',
        'landing.hero.selectService': 'Xizmatni tanlang',
        'landing.hero.searchGuides': 'Gidlarni qidirish',
        'landing.hero.verifiedGuides': 'Tasdiqlangan gidlar',
        'landing.hero.countries': 'Mamlakatlar',
        'landing.hero.averageRating': 'O\'rtacha reyting',
        'landing.topGuides.title': 'Eng yaxshi gidlar',
        'landing.topGuides.description': 'Eng tajribali va yuqori baholangan mahalliy mutaxassislar bilan tanishing',
        'landing.services.title': 'Mashhur xizmatlar',
        'landing.services.description': 'Jamiyatimizdan eng ko\'p so\'ralgan xizmatlarni o\'rganing',
        'landing.cities.title': 'Taniqli yo\'nalishlar',
        'landing.cities.description': 'Ushbu mashhur shaharlarda ajoyib tajribalarni kashf eting',
        'landing.features.title': 'Nima uchun UzGuide?',
        'landing.features.description': 'Haqiqiy mahalliy tajriba farqini his eting',
        'landing.features.verified': 'Tasdiqlangan gidlar',
        'landing.features.verifiedDesc': 'Barcha gidlarimiz xavfsizligingiz uchun tekshirilgan va tasdiqlangan',
        'landing.features.support': '24/7 qo\'llab-quvvatlash',
        'landing.features.supportDesc': 'Muammosiz sayohat tajribasi uchun 24 soat mijozlarni qo\'llab-quvvatlash',
        'landing.features.global': 'Global qamrov',
        'landing.features.globalDesc': '150+ yo\'nalishda mahalliy mutaxassislar bilan bog\'laning',
        'landing.cta.title': 'Sayohatingizni boshlashga tayyormisiz?',
        'landing.cta.description': 'Mahalliy gidlar bilan haqiqiy tajribalarni kashf etgan minglab sayohatchilar qatoriga qo\'shiling',
        'landing.cta.findGuide': 'Gidingizni toping',
        'landing.cta.becomeGuide': 'Gid bo\'ling',

        // Qo‘shimcha umumiy kalitlar
        'landing.topGuides.empty': 'Hozircha gidlar yo‘q',

        // Services
        'service.tourGuide': 'Sayohat gidi',
        'service.translator': 'Tarjimon',
        'service.photographer': 'Fotograf',
        'service.driver': 'Haydovchi/Taksi',
        'service.shoppingHelper': 'Xarid yordamchisi',
        'service.foodGuide': 'Ovqat gidi',
        'service.businessFixer': 'Biznes yordamchisi',
        'service.culturalExpert': 'Madaniyat mutaxassisi',
        'service.localExpert': 'Mahalliy mutaxassis',
        'service.interpreter': 'Tarjimon',
        'service.eventPlanner': 'Tadbir tashkilotchisi',
        'service.airportTransfer': 'Aeroport transferi',
        'service.groupTours': 'Guruh sayohatlari',

        // Search Page
        'search.title': 'Mukammal gidingizni toping',
        'search.placeholder': 'Joylashuv, xizmat yoki gid nomi bo\'yicha qidiring...',
        'search.filters': 'Filtrlar',
        'search.serviceType': 'Xizmat turi',
        'search.allServices': 'Barcha xizmatlar',
        'search.priceRange': 'Narx oralig\'i ($/soat)',
        'search.minRating': 'Minimal reyting',
        'search.availability': 'Mavjudlik',
        'search.availableNow': 'Hozir mavjud',
        'search.availableToday': 'Bugun mavjud',
        'search.availableWeek': 'Shu hafta mavjud',
        'search.languages': 'Tillar',
        'search.anyLanguage': 'Har qanday til',
        'search.guidesFound': 'gid topildi',
        'search.sortBy': 'Mos kelishiga qarab',
        'search.sortPrice': 'Narx: Pastdan yuqoriga',
        'search.sortPriceDesc': 'Narx: Yuqoridan pastga',
        'search.sortRating': 'Reyting: Yuqoridan pastga',
        'search.sortReviews': 'Ko\'p sharhlar',
        'search.verified': 'Tasdiqlangan',
        'search.viewProfile': 'Profilni ko\'rish',
        'search.bookNow': 'Hozir band qilish',
        'search.speaks': 'Gapiradi',
        'search.responds': 'Odatda javob beradi',

        // Guide Profile
        // Guide List (qidiruv)
        'guide.list.title': 'Gid topish',
        'guide.list.apply': 'Filtrlarni qo‘llash',
        'guide.list.placeholder': 'Ism, familiya bo‘yicha qidirish…',
        'guide.list.allCountries': 'Barcha mamlakatlar',
        'guide.list.anyRating': 'Har qanday reyting',
        'guide.list.search': 'Qidirish',
        'guide.list.clear': 'Tozalash',
        'guide.list.error': 'Gidlarni yuklashda xatolik',
        'guide.list.empty': 'Gidlar topilmadi',
        'guide.list.experience': 'Tajriba',
        'guide.list.years': 'yil',
        'guide.list.viewProfile': 'Profilni ko‘rish',
        'guide.list.prev': 'Oldingi',
        'guide.list.next': 'Keyingi',
        'guide.list.page': 'Sahifa',
        'guide.list.of': 'dan',

// Guide Detail
        'guide.detail.notFound': 'Gid topilmadi',
        'guide.detail.back': 'Qidiruvga qaytish',
        'guide.detail.chatWith': '{{name}} bilan chat',
        'guide.detail.theGuide': 'gid',
        'guide.detail.bookTitle': 'Ushbu gidni band qilish',
        'guide.detail.unavailable': 'Hozircha mavjud emas',
        'guide.detail.requestBooking': 'Band qilish so‘rovi',
        'guide.detail.signInToBook': 'Band qilish uchun kiring',
        'guide.detail.startDate': 'Boshlanish sanasi',
        'guide.detail.endDate': 'Tugash sanasi',
        'guide.detail.check': 'Mavjudligini tekshirish',
        'guide.detail.checking': 'Tekshirilmoqda...',
        'guide.detail.guests': 'Mehmonlar',
        'guide.detail.messageLabel': 'Gidga xabar (ixtiyoriy)',
        'guide.detail.messagePh': 'Rejangiz, xohishlaringiz, jadvalingiz haqida qisqacha yozing…',
        'guide.detail.preparing': 'Tayyorlanmoqda…',
        'guide.detail.submit': 'Band qilishni yuborish',
        'guide.detail.portfolio': 'Portfolio',
        'guide.detail.noPortfolio': 'Portfolio elementlari yo‘q',

// Guide Detail alert/result matnlari
        'guide.detail.resolveError': 'Gid profili hali aniqlanmadi.',
        'guide.detail.chooseDates': 'Avval boshlanish va tugash sanasini tanlang.',
        'guide.detail.availableOk': 'Ko‘rsatilgan sanalarda gid mavjud.',
        'guide.detail.availableNo': 'Ko‘rsatilgan sanalarda gid mavjud emas.',
        'guide.detail.availableFail': 'Mavjudlikni tekshirish muvaffaqiyatsiz.',
        'guide.detail.noGuideId': 'Gid ID aniqlanmadi. Sahifani yangilang yoki qayta urinib ko‘ring.',
        'guide.detail.selectDates': 'Iltimos, boshlanish va tugash sanalarini tanlang',
        'guide.detail.endAfterStart': 'Tugash sanasi boshlanish sanasidan keyin bo‘lishi kerak',
        'guide.detail.notAvailable': 'Gid mavjud emas. Avval mavjudligini tekshiring.',
        'guide.detail.redirecting': 'Band qilish formasiga yo‘naltirilmoqda…',

        // Booking – new keys
        'booking.errInvalidGuide': 'Noto‘g‘ri gid profili.',
        'booking.errGuideNotFound': 'Gid topilmadi',
        'booking.errChooseDates': 'Avval boshlanish va tugash sanasini tanlang.',
        'booking.availableOk': 'Mavjud ✅',
        'booking.availableNo': 'Mavjud emas',
        'booking.availableFail': 'Mavjudlikni tekshirishda xatolik',
        'booking.errNoGuide': 'Gid tanlanmagan.',
        'booking.errSelectDates': 'Iltimos, sanalarni tanlang.',
        'booking.errEndBeforeStart': 'Tugash sanasi boshlanish sanasidan oldin bo‘lishi mumkin emas.',
        'booking.errCountryRequired': 'Mamlakat majburiy.',
        'booking.creating': 'Band qilinmoqda...',
        'booking.created': 'Band qilindi! Gidingiz tez orada bog‘lanadi.',
        'booking.errCreateFailed': 'Band qilishda xatolik. Iltimos, qayta urinib ko‘ring.',
        'booking.errOnlyCompletedReview': 'Faqat yakunlangan band qilish uchun sharh qoldirish mumkin.',
        'booking.errReviewBookingNotFound': 'Sharh uchun band qilish topilmadi.',
        'booking.errSelectRating': 'Iltimos, reytingni tanlang',
        'booking.reviewSubmitted': 'Sharhingiz jo‘natildi. Rahmat!',
        'booking.errSubmitReview': 'Sharhni jo‘natib bo‘lmadi.',
        'booking.serviceSchedule': 'Xizmat va jadval',
        'booking.selectServiceSchedule': 'Xizmat va jadvalni tanlang',
        'booking.country': 'Mamlakat',
        'booking.city': 'Shahar',
        'booking.startDate': 'Boshlanish sanasi',
        'booking.endDate': 'Tugash sanasi',
        'booking.checkAvailability': 'Mavjudligini tekshirish',
        'booking.checking': 'Tekshirilmoqda...',
        'booking.checkHint': 'Davom etishdan oldin ixtiyoriy tekshiruv',
        'booking.notesLabel': 'Gid uchun eslatmalar',
        'booking.requestBooking': 'Band qilish so‘rovi',
        'booking.writeReview': 'Sharh yozish',
        'booking.rating': 'Reyting',
        'booking.commentOpt': 'Izoh (ixtiyoriy)',
        'booking.shareExperience': 'Tajribangiz bilan o‘rtoqlashing…',
        'booking.sending': 'Jo‘natilmoqda…',
        'booking.submitReview': 'Sharhni yuborish',
        'booking.summary': 'Band qilish xulosasi',
        'booking.rate': 'Narx',
        'booking.perHour': 'soat',
        'booking.perDay': 'kun',

        // Dashboard (mavjud + yangi)
        'dashboard.title': 'Mening kabineta',
        'dashboard.description': 'Bronlar, gidlar va sayohatlaringizni boshqaring',
        'dashboard.upcomingBookings': 'Yaqqin bronlar',
        'dashboard.pastBookings': 'O‘tgan bronlar',
        'dashboard.total': 'Jami',
        'dashboard.status': 'Holat',
        'dashboard.upcomingBookingsTitle': 'Yaqqin bronlar',
        'dashboard.noUpcoming': 'Yaqqin bronlar mavjud emas.',
        'dashboard.findGuide': 'Gid topish',
        'dashboard.planNext': 'va navbatdagi sayohatingizni rejalashtiring!',
        'dashboard.noPast': 'O‘tgan bronlar yo‘q',
        'dashboard.pageXofN': 'Sahifa {x} • Jami {n}',
        'dashboard.page': 'Sahifa {x}',
        'dashboard.myBookings': 'Bronlarim',
        'dashboard.profileInfo': 'Profil maʼlumotlari',
        'dashboard.refresh': 'Yangilash',

// Card actions
        'dashboard.cancel': 'Bekor qilish',
        'dashboard.markComplete': 'Tugallandi',
        'dashboard.leaveReview': 'Fikr qoldirish',

// Confirmations / statuses / errors
        'dashboard.confirmCancel': 'Ushbu bronni bekor qilasizmi?',
        'dashboard.confirmComplete': 'Ushbu bronni tugallangan deb belgilaysizmi?',
        'dashboard.statusCancelled': 'Bekor qilingan',
        'dashboard.statusCompleted': 'Tugallangan',
        'dashboard.errCancel': 'Bronni bekor qilib bo‘lmadi',
        'dashboard.errComplete': 'Bronni tugallab bo‘lmadi',
        'dashboard.errResolveProfile': 'Gid profilini aniqlab bo‘lmadi',
        'dashboard.errResolveReview': 'Sharh yo‘naltirishni aniqlab bo‘lmadi',

// Profile section
        'dashboard.avatarHint': 'JPG, PNG, GIF, WEBP • Maks 5MB',
        'dashboard.uploading': 'Yuklanmoqda...',
        'dashboard.uploadPhoto': 'Rasm yuklash',
        'dashboard.removePhoto': 'Rasmni o‘chirish',
        'dashboard.firstName': 'Ism',
        'dashboard.lastName': 'Familiya',
        'dashboard.emailReadonly': 'Email (faqat o‘qish)',
        'dashboard.phone': 'Telefon',
        'dashboard.saveChanges': 'O‘zgarishlarni saqlash',
        'dashboard.saving': 'Saqlanmoqda…',
        'dashboard.saved': 'Profil saqlandi',
        'dashboard.errSave': 'Profilni saqlab bo‘lmadi',
        'dashboard.avatarMax': 'Maks 5MB',
        'dashboard.avatarTypes': 'Iltimos JPG/PNG/GIF/WEBP tanlang',
        'dashboard.avatarUpdated': 'Avatar yangilandi',
        'dashboard.errAvatarUpload': 'Avatarni yuklashda xatolik',
        'dashboard.avatarRemoved': 'Avatar o‘chirildi',
        'dashboard.errAvatarRemove': 'Avatarni o‘chirib bo‘lmadi',

// Overlays
        'dashboard.cancelling': 'Bron bekor qilinmoqda…',
        'dashboard.completing': 'Bron tugallanmoqda…',

        // Guide – nav/labels
        'guide.nav.overview': 'Umumiy',
        'guide.nav.profileServices': 'Profil va xizmatlar',
        'guide.nav.analytics': 'Analitika',

        'guide.common.yourName': 'Ismingiz',
        'guide.common.tourist': 'Sayyoh',
        'guide.common.guest': 'Mehmon',
        'guide.common.service': 'Xizmat',
        'guide.common.scheduled': 'rejalashtirilgan',

// Overview
        'guide.overview.welcome': 'Xush kelibsiz, {name}!',
        'guide.overview.todayCount': 'Bugun {n} ta tur rejalashtirilgan',
        'guide.overview.yourRating': 'Sizning reytingingiz',
        'guide.overview.responseRate': 'Javob darajasi',
        'guide.overview.last30': 'Oxirgi 30 kun',
        'guide.overview.todaySchedule': 'Bugungi jadval',
        'guide.overview.noToursToday': 'Bugun turlar yo‘q',

// Bookings
        'guide.bookings.title': 'Bronlarni boshqarish',
        'guide.bookings.pending': 'Kutilayotgan so‘rovlar',
        'guide.bookings.confirmed': 'Tasdiqlangan bronlar',
        'guide.bookings.accept': 'Qabul qilish',
        'guide.bookings.decline': 'Rad etish',
        'guide.bookings.markCompleted': 'Tugallandi deb belgilash',
        'guide.bookings.noPending': 'Kutilayotgan so‘rovlar yo‘q',
        'guide.bookings.noConfirmed': 'Tasdiqlangan bronlar yo‘q',
        'guide.bookings.offer': 'Taklif',
        'guide.bookings.detailTitle': 'Bron tafsilotlari',
        'guide.bookings.status': 'Holat',
        'guide.bookings.tourist': 'Sayyoh',
        'guide.bookings.dates': 'Sanalar',
        'guide.bookings.location': 'Manzil',
        'guide.bookings.message': 'Xabar',
        'guide.bookings.declineTitle': 'So‘rovni rad etish',
        'guide.bookings.reasonOpt': 'Sabab (ixtiyoriy)',
        'guide.bookings.reasonPh': 'Masalan: Tanlangan sanalarda bandman',
        'guide.dashboard.bookingsRefreshed': 'Bronlar yangilandi',
        'guide.dashboard.acceptFailed': 'Bronni qabul qilib bo‘lmadi',
        'guide.dashboard.declineFailed': 'Bronni rad etib bo‘lmadi',
        'guide.dashboard.completeFailed': 'Tugallandi deb belgilab bo‘lmadi',

// Profile
        'guide.dashboard.profileInfo': 'Profil ma’lumotlari',
        'guide.profile.firstName': 'Ism',
        'guide.profile.lastName': 'Familiya',
        'guide.profile.emailReadonly': 'Email (faqat o‘qish)',
        'guide.profile.location': 'Joylashuv (mamlakat nomi yoki kodi)',
        'guide.profile.locationPh': 'masalan, Uzbekistan yoki UZ',
        'guide.profile.bio': 'Bio',
        'guide.profile.bioPh': 'O‘zingiz va tajribangiz haqida yozing...',
        'guide.profile.languages': 'Tillar (vergul bilan)',
        'guide.profile.languagesPh': 'masalan, English, Russian, Uzbek',
        'guide.profile.known': 'Mavjud',
        'guide.profile.langsNotLoaded': 'Til katalogi yuklanmadi.',
        'guide.profile.years': 'Tajriba yillari',

// Portfolio / Services
        'guide.service.item': 'Xizmat',
        'guide.service.order': 'Tartib: {n}',
        'guide.service.preview': 'Ko‘rish',
        'guide.service.noDesc': 'Tavsif yo‘q',
        'guide.service.empty': 'Portfolio bo‘sh',
        'guide.service.titlePh': 'masalan, Eski shahar piyoda sayri',
        'guide.service.descPh': 'Qisqa tavsif…',
        'guide.service.orderLabel': 'Tartib',
        'guide.service.imageReq': 'Rasm *',
        'guide.dashboard.portfolioCreated': 'Portfolio elementi yaratildi',
        'guide.dashboard.portfolioCreateFailed': 'Portfolio yaratib bo‘lmadi',
        'guide.dashboard.confirmDelete': 'Bu elementni o‘chirilsinmi?',
        'guide.dashboard.deleteFailed': 'O‘chirishda xatolik',
        'guide.dashboard.portfolioMax': 'Maks 10MB',
        'guide.dashboard.photoRequired': 'Rasm talab qilinadi',

// Photo / avatar
        'guide.dashboard.photoMax': 'Maks 5MB',
        'guide.dashboard.photoTypes': 'Iltimos JPG/PNG/GIF tanlang',
        'guide.dashboard.photoUpdated': 'Avatar yangilandi',
        'guide.dashboard.photoUploadFailed': 'Avatar yuklashda xatolik',
        'guide.dashboard.photoRemoved': 'Avatar o‘chirildi',
        'guide.dashboard.photoRemoveFailed': 'Avatarni o‘chirib bo‘lmadi',

// Earnings
        'guide.earn.thisMonth': 'Ushbu oy',
        'guide.earn.thisMonthShort': 'Ushbu oy',
        'guide.earn.totalBalance': 'Umumiy balans',
        'guide.earn.monthly': 'Oylik daromad',
        'guide.earn.average': 'O‘rtacha',
        'guide.earn.perBooking': 'Har bir bron uchun',
        'guide.earn.pendingShort': 'Kutilmoqda',
        'guide.earn.available': 'Mavjud',
        'guide.earn.transactions': 'Tranzaksiya tarixi',
        'guide.earn.export': 'Eksport',
        'guide.earn.date': 'Sana',
        'guide.earn.tourist': 'Sayyoh',
        'guide.earn.service': 'Xizmat',
        'guide.earn.amount': 'Miqdor',
        'guide.earn.status': 'Holat',
        'guide.earn.noTx': 'Tranzaksiyalar yo‘q',
        'guide.earn.withdraw': 'Yecharish ${amount}',

// Reviews
        'guide.reviews.count': 'ta sharh',
        'guide.reviews.none': 'Hozircha sharhlar yo‘q',

// Stats / analytics
        'guide.stats.week': 'Bu hafta bronlar',
        'guide.stats.month': 'Bu oy bronlar',
        'guide.stats.completion': 'Tugatish darajasi',
        'guide.stats.response': 'Javob darajasi',
        'guide.stats.popular': 'Eng mashhur xizmatlar',
        'guide.stats.noData': 'Maʼlumot yo‘q',
        'guide.stats.monthlyPerf': 'Oylik ko‘rsatkichlar',
        'guide.stats.chartPlaceholder': 'Analitika grafigi',

        // Chat (new/completed)
        'chat.title': 'Xabarlar',
        'chat.description': 'Gidlar va sayyohlar bilan suhbatlaringiz',
        'chat.searchConversations': 'Suhbatlarda qidirish...',
        'chat.onlineNow': 'Hozir onlayn',
        'chat.lastSeen': 'Oxirgi ko‘rilgan',
        'chat.bookingDetails': 'Band qilish tafsilotlari',
        'chat.typeMessage': 'Xabaringizni yozing…',
        'chat.aiTranslation': 'Ko‘p tilli suhbatlar uchun AI tarjima mavjud',
        'chat.photo': 'Foto',

        'chat.user': 'Foydalanuvchi',
        'chat.me': 'Men',
        'chat.errLoadMessages': 'Xabarlarni yuklab bo‘lmadi',
        'chat.errSend': 'Xabarni yuborib bo‘lmadi',
        'chat.noConversations': 'Suhbatlar yo‘q',
        'chat.loadOlder': 'Eski xabarlarni yuklash',
        'chat.selectConversation': 'Suhbatni tanlang',
        'chat.more': 'Qo‘shimcha',
        'chat.back': 'Ortga',
        'chat.send': 'Yuborish',
        'chat.emojis': 'Emoji',
        'chat.insertEmoji': 'Emoji qo‘shish',
        'chat.rtcEnabled': 'Real-time chat yoqilgan.',

        // Auth
        'auth.welcomeBack': 'Xush kelibsiz',
        'auth.createAccount': 'Hisobingizni yarating',
        'auth.signInDescription': 'Davom etish uchun hisobingizga kiring',
        'auth.signUpDescription': 'Minglab sayohatchilar va gidlar qatoriga qo\'shiling',
        'auth.joinAs': 'Men quyidagicha qo\'shilmoqchiman:',
        'auth.tourist': 'Turist',
        'auth.touristDesc': 'Mahalliy gidlarni toping va band qiling',
        'auth.guide': 'Gid',
        'auth.guideDesc': 'Mahalliy tajribangizni taklif eting',
        'auth.fullName': 'To\'liq ism',
        'auth.emailAddress': 'Email manzil',
        'auth.yourLocation': 'Sizning joylashuvingiz',
        'auth.password': 'Parol',
        'auth.confirmPassword': 'Parolni tasdiqlang',
        'auth.agreeTerms': 'Men quyidagilarga roziman',
        'auth.termsOfService': 'Xizmat shartlari',
        'auth.privacyPolicy': 'Maxfiylik siyosati',
        'auth.signIn': 'Kirish',
        // 'auth.createAccount': 'Hisob yaratish',
        'auth.noAccount': 'Hisobingiz yo\'qmi?',
        'auth.haveAccount': 'Hisobingiz bormi?',
        'auth.signUp': 'Ro\'yxatdan o\'tish',
        'auth.continueWith': 'Yoki davom eting',
        'auth.google': 'Google',
        'auth.facebook': 'Facebook',
        'auth.trustedBy': 'Minglab sayohatchilar tomonidan ishonilgan',
        'auth.secureVerified': 'Xavfsiz va tasdiqlangan',
        'auth.safe': '100% xavfsiz',

        // Footer
        'footer.description': 'Butun dunyo bo\'ylab tasdiqlangan mahalliy gidlar bilan bog\'laning. Haqiqiy tajribalarni kashf eting va unutilmas xotiralar yarating.',
        'footer.quickLinks': 'Tezkor havolalar',
        'footer.findGuides': 'Gidlarni topish',
        'footer.becomeGuide': 'Gid bo\'lish',
        'footer.aboutUs': 'Biz haqimizda',
        'footer.howItWorks': 'Qanday ishlaydi',
        'footer.safety': 'Xavfsizlik',
        'footer.support': 'Qo\'llab-quvvatlash',
        'footer.helpCenter': 'Yordam markazi',
        'footer.contactUs': 'Biz bilan bog\'laning',
        'footer.termsOfService': 'Xizmat shartlari',
        'footer.privacyPolicy': 'Maxfiylik siyosati',
        'footer.cancellationPolicy': 'Bekor qilish siyosati',
        'footer.contact': 'Aloqa',
        'footer.newsletter': 'Yangiliklar',
        'footer.yourEmail': 'Sizning emailingiz',
        'footer.subscribe': 'Obuna bo\'lish',
        'footer.allRightsReserved': 'Barcha huquqlar himoyalangan.',
        'footer.sitemap': 'Sayt xaritasi',
        'footer.accessibility': 'Foydalanish imkoniyati',
        'footer.cookiePolicy': 'Cookie siyosati',

        // Common
        'common.loading': 'Yuklanmoqda...',
        'common.error': 'Xato',
        'common.success': 'Muvaffaqiyat',
        'common.cancel': 'Bekor qilish',
        'common.save': 'Saqlash',
        'common.edit': 'Tahrirlash',
        'common.delete': 'O\'chirish',
        'common.view': 'Ko\'rish',
        'common.close': 'Yopish',
        'common.next': 'Keyingi',
        'common.previous': 'Oldingi',
        'common.search': 'Qidirish',
        'common.filter': 'Filtr',
        'common.sort': 'Saralash',
        'common.date': 'Sana',
        'common.time': 'Vaqt',
        'common.location': 'Joylashuv',
        'common.price': 'Narx',
        'common.rating': 'Reyting',
        'common.reviews': 'Sharhlar',
        'common.hour': 'soat',
        'common.hours': 'soatlar',
        'common.min': 'Min',
        'common.max': 'Maks',
        'common.all': 'Hammasi',
        'common.none': 'Yo\'q',
        'common.yes': 'Ha',
        'common.no': 'Yo\'q',
        'common.ok': 'OK',
    },
    ru: {
        // Navigation
        'nav.findGuides': 'Найти гидов',
        'nav.becomeGuide': 'Стать гидом',
        'nav.signIn': 'Войти',
        'nav.messages': 'Сообщения',
        'nav.dashboard': 'Панель управления',
        'nav.logout': 'Выйти',
        'nav.searchPlaceholder': 'Поиск места назначения',

        // Landing Page
        'landing.hero.title': 'Связь с местными',
        'landing.hero.subtitle': 'Экспертами-гидами',
        'landing.hero.description': 'Откройте подлинные впечатления с проверенными местными гидами по всему миру',
        'landing.hero.whereTo': 'Куда вы хотите отправиться?',
        'landing.hero.selectService': 'Выберите услугу',
        'landing.hero.searchGuides': 'Поиск гидов',
        'landing.hero.verifiedGuides': 'Проверенные гиды',
        'landing.hero.countries': 'Страны',
        'landing.hero.averageRating': 'Средний рейтинг',
        'landing.topGuides.title': 'Лучшие гиды',
        'landing.topGuides.description': 'Познакомьтесь с нашими самыми опытными и высокорейтинговыми местными экспертами',
        'landing.services.title': 'Популярные услуги',
        'landing.services.description': 'Ознакомьтесь с наиболее востребованными услугами нашего сообщества',
        'landing.cities.title': 'Популярные направления',
        'landing.cities.description': 'Откройте удивительные впечатления в этих популярных городах',
        'landing.features.title': 'Почему выбирают UzGuide?',
        'landing.features.description': 'Ощутите разницу подлинного местного опыта',
        'landing.features.verified': 'Проверенные гиды',
        'landing.features.verifiedDesc': 'Все наши гиды проходят тщательную проверку для вашей безопасности',
        'landing.features.support': 'Круглосуточная поддержка',
        'landing.features.supportDesc': 'Круглосуточная поддержка клиентов для беспроблемного путешествия',
        'landing.features.global': 'Глобальное покрытие',
        'landing.features.globalDesc': 'Связь с местными экспертами в более чем 150 направлениях по всему миру',
        'landing.cta.title': 'Готовы начать свое путешествие?',
        'landing.cta.description': 'Присоединяйтесь к тысячам путешественников, которые открыли подлинные впечатления с местными гидами',
        'landing.cta.findGuide': 'Найти гида',
        'landing.cta.becomeGuide': 'Стать гидом',

        // Additional common keys
        'landing.topGuides.empty': 'Пока нет гидов',

        // Services
        'service.tourGuide': 'Тур гид',
        'service.translator': 'Переводчик',
        'service.photographer': 'Фотограф',
        'service.driver': 'Водитель/Такси',
        'service.shoppingHelper': 'Помощник по покупкам',
        'service.foodGuide': 'Гастрономический гид',
        'service.businessFixer': 'Бизнес-помощник',
        'service.culturalExpert': 'Эксперт по культуре',
        'service.localExpert': 'Местный эксперт',
        'service.interpreter': 'Устный переводчик',
        'service.eventPlanner': 'Организатор мероприятий',
        'service.airportTransfer': 'Трансфер из аэропорта',
        'service.groupTours': 'Групповые туры',

        // Search Page
        'search.title': 'Найдите идеального гида',
        'search.placeholder': 'Поиск по местоположению, услуге или имени гида...',
        'search.filters': 'Фильтры',
        'search.serviceType': 'Тип услуги',
        'search.allServices': 'Все услуги',
        'search.priceRange': 'Диапазон цен ($/час)',
        'search.minRating': 'Минимальный рейтинг',
        'search.availability': 'Доступность',
        'search.availableNow': 'Доступен сейчас',
        'search.availableToday': 'Доступен сегодня',
        'search.availableWeek': 'Доступен на этой неделе',
        'search.languages': 'Языки',
        'search.anyLanguage': 'Любой язык',
        'search.guidesFound': 'гидов найдено',
        'search.sortBy': 'Сортировать по релевантности',
        'search.sortPrice': 'Цена: от низкой к высокой',
        'search.sortPriceDesc': 'Цена: от высокой к низкой',
        'search.sortRating': 'Рейтинг: от высокого к низкому',
        'search.sortReviews': 'Больше всего отзывов',
        'search.verified': 'Проверенный',
        'search.viewProfile': 'Посмотреть профиль',
        'search.bookNow': 'Забронировать сейчас',
        'search.speaks': 'Говорит',
        'search.responds': 'Обычно отвечает',

        // Guide List (search)
        'guide.list.title': 'Найти гида',
        'guide.list.apply': 'Применить фильтры',
        'guide.list.placeholder': 'Поиск по имени, фамилии…',
        'guide.list.allCountries': 'Все страны',
        'guide.list.anyRating': 'Любой рейтинг',
        'guide.list.search': 'Поиск',
        'guide.list.clear': 'Очистить',
        'guide.list.error': 'Не удалось загрузить гидов',
        'guide.list.empty': 'Гиды не найдены',
        'guide.list.experience': 'Опыт',
        'guide.list.years': 'лет',
        'guide.list.viewProfile': 'Посмотреть профиль',
        'guide.list.prev': 'Предыдущая',
        'guide.list.next': 'Следующая',
        'guide.list.page': 'Страница',
        'guide.list.of': 'из',

        // Guide Detail
        'guide.detail.notFound': 'Гид не найден',
        'guide.detail.back': 'Вернуться к поиску',
        'guide.detail.chatWith': 'Чат с {{name}}',
        'guide.detail.theGuide': 'гид',
        'guide.detail.bookTitle': 'Забронировать этого гида',
        'guide.detail.unavailable': 'В настоящее время недоступен',
        'guide.detail.requestBooking': 'Запросить бронирование',
        'guide.detail.signInToBook': 'Войдите, чтобы забронировать',
        'guide.detail.startDate': 'Дата начала',
        'guide.detail.endDate': 'Дата окончания',
        'guide.detail.check': 'Проверить доступность',
        'guide.detail.checking': 'Проверка...',
        'guide.detail.guests': 'Гости',
        'guide.detail.messageLabel': 'Сообщение гиду (необязательно)',
        'guide.detail.messagePh': 'Расскажите немного о вашем плане, предпочтениях, расписании…',
        'guide.detail.preparing': 'Подготовка…',
        'guide.detail.submit': 'Отправить бронирование',
        'guide.detail.portfolio': 'Портфолио',
        'guide.detail.noPortfolio': 'Нет элементов портфолио',

        // Guide Detail alerts/results
        'guide.detail.resolveError': 'Профиль гида еще не определен.',
        'guide.detail.chooseDates': 'Сначала выберите даты начала и окончания.',
        'guide.detail.availableOk': 'Гид доступен на эти даты.',
        'guide.detail.availableNo': 'Гид недоступен на эти даты.',
        'guide.detail.availableFail': 'Не удалось проверить доступность.',
        'guide.detail.noGuideId': 'Идентификатор гида не определен. Обновите страницу или попробуйте снова.',
        'guide.detail.selectDates': 'Пожалуйста, выберите даты начала и окончания',
        'guide.detail.endAfterStart': 'Дата окончания должна быть после даты начала',
        'guide.detail.notAvailable': 'Гид недоступен. Пожалуйста, сначала проверьте доступность.',
        'guide.detail.redirecting': 'Перенаправление на форму бронирования…',

        // Booking – new keys
        'booking.errInvalidGuide': 'Недействительный профиль гида.',
        'booking.errGuideNotFound': 'Гид не найден',
        'booking.errChooseDates': 'Сначала выберите даты начала и окончания.',
        'booking.availableOk': 'Доступен ✅',
        'booking.availableNo': 'Недоступен',
        'booking.availableFail': 'Не удалось проверить доступность',
        'booking.errNoGuide': 'Гид не выбран.',
        'booking.errSelectDates': 'Пожалуйста, выберите даты.',
        'booking.errEndBeforeStart': 'Дата окончания не может быть раньше даты начала.',
        'booking.errCountryRequired': 'Страна обязательна.',
        'booking.creating': 'Создание бронирования...',
        'booking.created': 'Бронирование создано! Ваш гид скоро свяжется с вами.',
        'booking.errCreateFailed': 'Не удалось создать бронирование. Пожалуйста, попробуйте снова.',
        'booking.errOnlyCompletedReview': 'Вы можете оставить отзыв только для завершенного бронирования.',
        'booking.errReviewBookingNotFound': 'Бронирование для отзыва не найдено.',
        'booking.errSelectRating': 'Пожалуйста, выберите рейтинг',
        'booking.reviewSubmitted': 'Отзыв отправлен. Спасибо!',
        'booking.errSubmitReview': 'Не удалось отправить отзыв.',
        'booking.serviceSchedule': 'Услуга и расписание',
        'booking.selectServiceSchedule': 'Выберите услугу и расписание',
        'booking.country': 'Страна',
        'booking.city': 'Город',
        'booking.startDate': 'Дата начала',
        'booking.endDate': 'Дата окончания',
        'booking.checkAvailability': 'Проверить доступность',
        'booking.checking': 'Проверка...',
        'booking.checkHint': 'Необязательная проверка перед продолжением',
        'booking.notesLabel': 'Заметки для вашего гида',
        'booking.requestBooking': 'Запросить бронирование',
        'booking.writeReview': 'Написать отзыв',
        'booking.rating': 'Рейтинг',
        'booking.commentOpt': 'Комментарий (необязательно)',
        'booking.shareExperience': 'Поделитесь своим опытом…',
        'booking.sending': 'Отправка…',
        'booking.submitReview': 'Отправить отзыв',
        'booking.summary': 'Сводка бронирования',
        'booking.rate': 'Ставка',
        'booking.perHour': 'час',
        'booking.perDay': 'день',

        // Dashboard
        'dashboard.title': 'Моя панель управления',
        'dashboard.description': 'Управляйте своими бронированиями, гидами и путешествиями',
        'dashboard.upcomingBookings': 'Предстоящие бронирования',
        'dashboard.pastBookings': 'Прошлые бронирования',
        'dashboard.total': 'Всего',
        'dashboard.status': 'Статус',
        'dashboard.upcomingBookingsTitle': 'Предстоящие бронирования',
        'dashboard.noUpcoming': 'Нет предстоящих бронирований.',
        'dashboard.findGuide': 'Найти гида',
        'dashboard.planNext': 'и спланируйте следующее путешествие!',
        'dashboard.noPast': 'Нет прошлых бронирований',
        'dashboard.pageXofN': 'Страница {x} • Всего {n}',
        'dashboard.page': 'Страница {x}',
        'dashboard.myBookings': 'Мои бронирования',
        'dashboard.profileInfo': 'Информация о профиле',
        'dashboard.refresh': 'Обновить',

        // Card actions
        'dashboard.cancel': 'Отменить',
        'dashboard.markComplete': 'Завершить',
        'dashboard.leaveReview': 'Оставить отзыв',

        // Confirmations / statuses / errors
        'dashboard.confirmCancel': 'Отменить это бронирование?',
        'dashboard.confirmComplete': 'Отметить это бронирование как завершенное?',
        'dashboard.statusCancelled': 'Отменено',
        'dashboard.statusCompleted': 'Завершено',
        'dashboard.errCancel': 'Не удалось отменить бронирование',
        'dashboard.errComplete': 'Не удалось завершить бронирование',
        'dashboard.errResolveProfile': 'Не удалось определить профиль гида',
        'dashboard.errResolveReview': 'Не удалось определить цель отзыва',

        // Profile section
        'dashboard.avatarHint': 'JPG, PNG, GIF, WEBP • Макс 5MB',
        'dashboard.uploading': 'Загрузка...',
        'dashboard.uploadPhoto': 'Загрузить фото',
        'dashboard.removePhoto': 'Удалить фото',
        'dashboard.firstName': 'Имя',
        'dashboard.lastName': 'Фамилия',
        'dashboard.emailReadonly': 'Email (только чтение)',
        'dashboard.phone': 'Телефон',
        'dashboard.saveChanges': 'Сохранить изменения',
        'dashboard.saving': 'Сохранение…',
        'dashboard.saved': 'Профиль сохранен',
        'dashboard.errSave': 'Не удалось сохранить профиль',
        'dashboard.avatarMax': 'Макс 5MB',
        'dashboard.avatarTypes': 'Пожалуйста, выберите JPG/PNG/GIF/WEBP',
        'dashboard.avatarUpdated': 'Аватар обновлен',
        'dashboard.errAvatarUpload': 'Ошибка загрузки аватара',
        'dashboard.avatarRemoved': 'Аватар удален',
        'dashboard.errAvatarRemove': 'Не удалось удалить аватар',

        // Overlays
        'dashboard.cancelling': 'Отмена бронирования…',
        'dashboard.completing': 'Завершение бронирования…',

        // Guide – nav/labels
        'guide.nav.overview': 'Обзор',
        'guide.nav.profileServices': 'Профиль и услуги',
        'guide.nav.analytics': 'Аналитика',

        'guide.common.yourName': 'Ваше имя',
        'guide.common.tourist': 'Турист',
        'guide.common.guest': 'Гость',
        'guide.common.service': 'Услуга',
        'guide.common.scheduled': 'запланировано',

        // Overview
        'guide.overview.welcome': 'Добро пожаловать, {name}!',
        'guide.overview.todayCount': 'У вас запланировано {n} туров на сегодня',
        'guide.overview.yourRating': 'Ваш рейтинг',
        'guide.overview.responseRate': 'Скорость ответа',
        'guide.overview.last30': 'Последние 30 дней',
        'guide.overview.todaySchedule': 'Расписание на сегодня',
        'guide.overview.noToursToday': 'На сегодня туры не запланированы',

        // Bookings
        'guide.bookings.title': 'Управление бронированиями',
        'guide.bookings.pending': 'Ожидающие запросы',
        'guide.bookings.confirmed': 'Подтвержденные бронирования',
        'guide.bookings.accept': 'Принять',
        'guide.bookings.decline': 'Отклонить',
        'guide.bookings.markCompleted': 'Отметить как завершенное',
        'guide.bookings.noPending': 'Нет ожидающих запросов',
        'guide.bookings.noConfirmed': 'Нет подтвержденных бронирований',
        'guide.bookings.offer': 'Предложение',
        'guide.bookings.detailTitle': 'Детали бронирования',
        'guide.bookings.status': 'Статус',
        'guide.bookings.tourist': 'Турист',
        'guide.bookings.dates': 'Даты',
        'guide.bookings.location': 'Местоположение',
        'guide.bookings.message': 'Сообщение',
        'guide.bookings.declineTitle': 'Отклонить запрос',
        'guide.bookings.reasonOpt': 'Причина (необязательно)',
        'guide.bookings.reasonPh': 'Например, недоступен в выбранные даты',
        'guide.dashboard.bookingsRefreshed': 'Бронирования обновлены',
        'guide.dashboard.acceptFailed': 'Не удалось принять бронирование',
        'guide.dashboard.declineFailed': 'Не удалось отклонить бронирование',
        'guide.dashboard.completeFailed': 'Не удалось отметить как завершенное',

        // Profile
        'guide.dashboard.profileInfo': 'Информация о профиле',
        'guide.profile.firstName': 'Имя',
        'guide.profile.lastName': 'Фамилия',
        'guide.profile.emailReadonly': 'Email (только чтение)',
        'guide.profile.location': 'Местоположение (название страны или код)',
        'guide.profile.locationPh': 'например, Узбекистан или UZ',
        'guide.profile.bio': 'Биография',
        'guide.profile.bioPh': 'Расскажите о себе и своем опыте...',
        'guide.profile.languages': 'Языки (через запятую)',
        'guide.profile.languagesPh': 'например, английский, русский, узбекский',
        'guide.profile.known': 'Известно',
        'guide.profile.langsNotLoaded': 'Каталог языков не загружен.',
        'guide.profile.years': 'Годы опыта',

        // Portfolio/services
        'guide.service.item': 'Элемент',
        'guide.service.order': 'Порядок: {n}',
        'guide.service.preview': 'Предпросмотр',
        'guide.service.noDesc': 'Нет описания',
        'guide.service.empty': 'Нет элементов портфолио',
        'guide.service.titlePh': 'например, прогулка по старому городу',
        'guide.service.descPh': 'Краткое описание…',
        'guide.service.orderLabel': 'Порядок',
        'guide.service.imageReq': 'Изображение *',
        'guide.dashboard.portfolioCreated': 'Элемент портфолио создан',
        'guide.dashboard.portfolioCreateFailed': 'Не удалось создать элемент портфолио',
        'guide.dashboard.confirmDelete': 'Удалить этот элемент?',
        'guide.dashboard.deleteFailed': 'Ошибка удаления',
        'guide.dashboard.portfolioMax': 'Макс 10MB',
        'guide.dashboard.photoRequired': 'Требуется изображение',

        // Photo / avatar
        'guide.dashboard.photoMax': 'Макс 5MB',
        'guide.dashboard.photoTypes': 'Пожалуйста, выберите JPG/PNG/GIF',
        'guide.dashboard.photoUpdated': 'Аватар обновлен',
        'guide.dashboard.photoUploadFailed': 'Ошибка загрузки аватара',
        'guide.dashboard.photoRemoved': 'Аватар удален',
        'guide.dashboard.photoRemoveFailed': 'Не удалось удалить аватар',

        // Earnings
        'guide.earn.thisMonth': 'Этот месяц',
        'guide.earn.thisMonthShort': 'Этот месяц',
        'guide.earn.totalBalance': 'Общий баланс',
        'guide.earn.monthly': 'Месячный доход',
        'guide.earn.average': 'Средний',
        'guide.earn.perBooking': 'За бронирование',
        'guide.earn.pendingShort': 'Ожидает',
        'guide.earn.available': 'Доступно',
        'guide.earn.transactions': 'История транзакций',
        'guide.earn.export': 'Экспорт',
        'guide.earn.date': 'Дата',
        'guide.earn.tourist': 'Турист',
        'guide.earn.service': 'Услуга',
        'guide.earn.amount': 'Сумма',
        'guide.earn.status': 'Статус',
        'guide.earn.noTx': 'Нет транзакций',
        'guide.earn.withdraw': 'Вывести ${amount}',

        // Reviews
        'guide.reviews.count': 'отзывов',
        'guide.reviews.none': 'Пока нет отзывов',

        // Stats / analytics
        'guide.stats.week': 'Бронирования на этой неделе',
        'guide.stats.month': 'Бронирования в этом месяце',
        'guide.stats.completion': 'Процент завершения',
        'guide.stats.response': 'Скорость ответа',
        'guide.stats.popular': 'Самые популярные услуги',
        'guide.stats.noData': 'Нет данных',
        'guide.stats.monthlyPerf': 'Месячная производительность',
        'guide.stats.chartPlaceholder': 'График аналитики производительности',

        // Common guide extras
        'guide.common.guestPlural': 'гостей',

        // Chat
        'chat.title': 'Сообщения',
        'chat.description': 'Ваши беседы с гидами и туристами',
        'chat.searchConversations': 'Поиск в беседах...',
        'chat.onlineNow': 'Сейчас онлайн',
        'chat.lastSeen': 'Последний раз был',
        'chat.bookingDetails': 'Детали бронирования',
        'chat.typeMessage': 'Введите ваше сообщение…',
        'chat.aiTranslation': 'Доступен ИИ-перевод для многоязычных бесед',
        'chat.photo': 'Фото',

        'chat.user': 'Пользователь',
        'chat.me': 'Я',
        'chat.errLoadMessages': 'Не удалось загрузить сообщения',
        'chat.errSend': 'Не удалось отправить сообщение',
        'chat.noConversations': 'Нет бесед',
        'chat.loadOlder': 'Загрузить старые сообщения',
        'chat.selectConversation': 'Выберите беседу',
        'chat.more': 'Больше опций',
        'chat.back': 'Назад',
        'chat.send': 'Отправить',
        'chat.emojis': 'Эмодзи',
        'chat.insertEmoji': 'Вставить эмодзи',
        'chat.rtcEnabled': 'Чат в реальном времени включен.',

        // Auth
        'auth.welcomeBack': 'Добро пожаловать обратно',
        'auth.createAccount': 'Создайте аккаунт',
        'auth.signInDescription': 'Войдите в свой аккаунт, чтобы продолжить',
        'auth.signUpDescription': 'Присоединяйтесь к тысячам путешественников и гидов по всему миру',
        'auth.joinAs': 'Я хочу присоединиться как:',
        'auth.tourist': 'Турист',
        'auth.touristDesc': 'Найти и забронировать местных гидов',
        'auth.guide': 'Гид',
        'auth.guideDesc': 'Предложить свой местный опыт',
        'auth.fullName': 'Полное имя',
        'auth.emailAddress': 'Адрес электронной почты',
        'auth.yourLocation': 'Ваше местоположение',
        'auth.password': 'Пароль',
        'auth.confirmPassword': 'Подтвердите пароль',
        'auth.agreeTerms': 'Я согласен с',
        'auth.termsOfService': 'Условиями обслуживания',
        'auth.privacyPolicy': 'Политикой конфиденциальности',
        'auth.signIn': 'Войти',
        'auth.noAccount': 'Нет аккаунта?',
        'auth.haveAccount': 'Уже есть аккаунт?',
        'auth.signUp': 'Зарегистрироваться',
        'auth.continueWith': 'Или продолжить через',
        'auth.google': 'Google',
        'auth.facebook': 'Facebook',
        'auth.trustedBy': 'Доверяют тысячи путешественников по всему миру',
        'auth.secureVerified': 'Безопасно и проверено',
        'auth.safe': '100% безопасно',

        // Footer
        'footer.description': 'Связь с проверенными местными гидами по всему миру. Откройте подлинные впечатления и создайте незабываемые воспоминания.',
        'footer.quickLinks': 'Быстрые ссылки',
        'footer.findGuides': 'Найти гидов',
        'footer.becomeGuide': 'Стать гидом',
        'footer.aboutUs': 'О нас',
        'footer.howItWorks': 'Как это работает',
        'footer.safety': 'Безопасность',
        'footer.support': 'Поддержка',
        'footer.helpCenter': 'Центр помощи',
        'footer.contactUs': 'Связаться с нами',
        'footer.termsOfService': 'Условия обслуживания',
        'footer.privacyPolicy': 'Политика конфиденциальности',
        'footer.cancellationPolicy': 'Политика отмены',
        'footer.contact': 'Контакты',
        'footer.newsletter': 'Новостная рассылка',
        'footer.yourEmail': 'Ваш email',
        'footer.subscribe': 'Подписаться',
        'footer.allRightsReserved': 'Все права защищены.',
        'footer.sitemap': 'Карта сайта',
        'footer.accessibility': 'Доступность',
        'footer.cookiePolicy': 'Политика использования cookies',

        // Common
        'common.loading': 'Загрузка...',
        'common.error': 'Ошибка',
        'common.success': 'Успех',
        'common.cancel': 'Отменить',
        'common.save': 'Сохранить',
        'common.edit': 'Редактировать',
        'common.delete': 'Удалить',
        'common.view': 'Посмотреть',
        'common.close': 'Закрыть',
        'common.next': 'Далее',
        'common.previous': 'Назад',
        'common.search': 'Поиск',
        'common.filter': 'Фильтр',
        'common.sort': 'Сортировка',
        'common.date': 'Дата',
        'common.time': 'Время',
        'common.location': 'Местоположение',
        'common.price': 'Цена',
        'common.rating': 'Рейтинг',
        'common.reviews': 'Отзывы',
        'common.hour': 'час',
        'common.hours': 'часов',
        'common.min': 'Мин',
        'common.max': 'Макс',
        'common.all': 'Все',
        'common.none': 'Нет',
        'common.yes': 'Да',
        'common.no': 'Нет',
        'common.ok': 'ОК',
    },
    kz: {
        // Navigation
        'nav.findGuides': 'Гидтерді табу',
        'nav.becomeGuide': 'Гид болу',
        'nav.signIn': 'Кіру',
        'nav.messages': 'Хабарламалар',
        'nav.dashboard': 'Басқару тақтасы',
        'nav.logout': 'Шығу',
        'nav.searchPlaceholder': 'Қайда баруды іздеу',

        // Landing Page
        'landing.hero.title': 'Жергілікті мамандармен байланысыңыз',
        'landing.hero.subtitle': 'Сарапшы гидтер',
        'landing.hero.description': 'Бүкіл әлем бойынша расталған жергілікті гидтермен шынайы тәжірибелерді ашыңыз',
        'landing.hero.whereTo': 'Қайда барғыңыз келеді?',
        'landing.hero.selectService': 'Қызметті таңдаңыз',
        'landing.hero.searchGuides': 'Гидтерді іздеу',
        'landing.hero.verifiedGuides': 'Расталған гидтер',
        'landing.hero.countries': 'Елдер',
        'landing.hero.averageRating': 'Орташа рейтинг',
        'landing.topGuides.title': 'Ең жоғары бағаланған гидтер',
        'landing.topGuides.description': 'Біздің ең тәжірибелі және жоғары бағаланған жергілікті мамандармен танысыңыз',
        'landing.services.title': 'Танымал қызметтер',
        'landing.services.description': 'Қауымдастығымыздан ең көп сұралған қызметтерді зерттеңіз',
        'landing.cities.title': 'Танымал бағыттар',
        'landing.cities.description': 'Осы танымал қалаларда керемет тәжірибелерді ашыңыз',
        'landing.features.title': 'Неліктен UzGuide таңдау керек?',
        'landing.features.description': 'Шынайы жергілікті тәжірибенің айырмашылығын сезіңіз',
        'landing.features.verified': 'Расталған гидтер',
        'landing.features.verifiedDesc': 'Барлық гидтер сіздің қауіпсіздігіңіз үшін мұқият тексерілген және расталған',
        'landing.features.support': '24/7 қолдау',
        'landing.features.supportDesc': 'Тегіс саяхат тәжірибесі үшін тәулік бойы клиенттерді қолдау',
        'landing.features.global': 'Жаһандық қамту',
        'landing.features.globalDesc': '150+ бағытта жергілікті мамандармен байланысыңыз',
        'landing.cta.title': 'Саяхатыңызды бастауға дайынсыз ба?',
        'landing.cta.description': 'Жергілікті гидтермен шынайы тәжірибелерді ашқан мыңдаған саяхатшылар қатарына қосылыңыз',
        'landing.cta.findGuide': 'Гидті табыңыз',
        'landing.cta.becomeGuide': 'Гид болыңыз',

        // Additional common keys
        'landing.topGuides.empty': 'Әзірге гидтер жоқ',

        // Services
        'service.tourGuide': 'Тур гиді',
        'service.translator': 'Аудармашы',
        'service.photographer': 'Фотограф',
        'service.driver': 'Жүргізуші/Такси',
        'service.shoppingHelper': 'Сауда көмекшісі',
        'service.foodGuide': 'Тамақ гиді',
        'service.businessFixer': 'Бизнес көмекшісі',
        'service.culturalExpert': 'Мәдениет маманы',
        'service.localExpert': 'Жергілікті маман',
        'service.interpreter': 'Ауызша аудармашы',
        'service.eventPlanner': 'Іс-шара ұйымдастырушысы',
        'service.airportTransfer': 'Әуежай трансфері',
        'service.groupTours': 'Топтық турлар',

        // Search Page
        'search.title': 'Өзіңізге ыңғайлы гидті табыңыз',
        'search.placeholder': 'Орын, қызмет немесе гидтің аты бойынша іздеу...',
        'search.filters': 'Сүзгілер',
        'search.serviceType': 'Қызмет түрі',
        'search.allServices': 'Барлық қызметтер',
        'search.priceRange': 'Баға диапазоны ($/сағат)',
        'search.minRating': 'Ең төменгі рейтинг',
        'search.availability': 'Қолжетімділік',
        'search.availableNow': 'Қазір қолжетімді',
        'search.availableToday': 'Бүгін қолжетімді',
        'search.availableWeek': 'Осы аптада қолжетімді',
        'search.languages': 'Тілдер',
        'search.anyLanguage': 'Кез келген тіл',
        'search.guidesFound': 'гид табылды',
        'search.sortBy': 'Сәйкестік бойынша сұрыптау',
        'search.sortPrice': 'Баға: төменнен жоғарыға',
        'search.sortPriceDesc': 'Баға: жоғарыдан төменге',
        'search.sortRating': 'Рейтинг: жоғарыдан төменге',
        'search.sortReviews': 'Ең көп пікірлер',
        'search.verified': 'Расталған',
        'search.viewProfile': 'Профильді қарау',
        'search.bookNow': 'Қазір брондау',
        'search.speaks': 'Сөйлейді',
        'search.responds': 'Әдетте жауап береді',

        // Guide List (search)
        'guide.list.title': 'Гид табу',
        'guide.list.apply': 'Сүзгілерді қолдану',
        'guide.list.placeholder': 'Аты, тегі бойынша іздеу…',
        'guide.list.allCountries': 'Барлық елдер',
        'guide.list.anyRating': 'Кез келген рейтинг',
        'guide.list.search': 'Іздеу',
        'guide.list.clear': 'Тазалау',
        'guide.list.error': 'Гидтерді жүктеу сәтсіз аяқталды',
        'guide.list.empty': 'Гидтер табылмады',
        'guide.list.experience': 'Тәжірибе',
        'guide.list.years': 'жыл',
        'guide.list.viewProfile': 'Профильді қарау',
        'guide.list.prev': 'Алдыңғы',
        'guide.list.next': 'Келесі',
        'guide.list.page': 'Бет',
        'guide.list.of': '-дан',

        // Guide Detail
        'guide.detail.notFound': 'Гид табылмады',
        'guide.detail.back': 'Іздеуге қайта оралу',
        'guide.detail.chatWith': '{{name}}мен чат',
        'guide.detail.theGuide': 'гид',
        'guide.detail.bookTitle': 'Осы гидті брондау',
        'guide.detail.unavailable': 'Қазіргі уақытта қолжетімді емес',
        'guide.detail.requestBooking': 'Брондау сұрау',
        'guide.detail.signInToBook': 'Брондау үшін кіріңіз',
        'guide.detail.startDate': 'Басталу күні',
        'guide.detail.endDate': 'Аяқталу күні',
        'guide.detail.check': 'Қолжетімділікті тексеру',
        'guide.detail.checking': 'Тексерілуде...',
        'guide.detail.guests': 'Қонақтар',
        'guide.detail.messageLabel': 'Гидке хабарлама (міндетті емес)',
        'guide.detail.messagePh': 'Жоспарыңыз, қалауларыңыз, кестеңіз туралы қысқаша айтыңыз…',
        'guide.detail.preparing': 'Дайындық…',
        'guide.detail.submit': 'Брондауды жіберу',
        'guide.detail.portfolio': 'Портфолио',
        'guide.detail.noPortfolio': 'Портфолио элементтері жоқ',

        // Guide Detail alerts/results
        'guide.detail.resolveError': 'Гид профилі әлі анықталмаған.',
        'guide.detail.chooseDates': 'Алдымен басталу және аяқталу күндерін таңдаңыз.',
        'guide.detail.availableOk': 'Гид осы күндерде қолжетімді.',
        'guide.detail.availableNo': 'Гид осы күндерде қолжетімді емес.',
        'guide.detail.availableFail': 'Қолжетімділікті тексеру сәтсіз аяқталды.',
        'guide.detail.noGuideId': 'Гидтің ID анықталмады. Бетті жаңартыңыз немесе қайта көріңіз.',
        'guide.detail.selectDates': 'Басталу және аяқталу күндерін таңдаңыз',
        'guide.detail.endAfterStart': 'Аяқталу күні басталу күнінен кейін болуы керек',
        'guide.detail.notAvailable': 'Гид қолжетімді емес. Алдымен қолжетімділікті тексеріңіз.',
        'guide.detail.redirecting': 'Брондау формасына қайта бағытталуда…',

        // Booking – new keys
        'booking.errInvalidGuide': 'Жарамсыз гид профилі.',
        'booking.errGuideNotFound': 'Гид табылмады',
        'booking.errChooseDates': 'Алдымен басталу және аяқталу күндерін таңдаңыз.',
        'booking.availableOk': 'Қолжетімді ✅',
        'booking.availableNo': 'Қолжетімді емес',
        'booking.availableFail': 'Қолжетімділікті тексеру сәтсіз аяқталды',
        'booking.errNoGuide': 'Гид таңдалмаған.',
        'booking.errSelectDates': 'Күндерді таңдаңыз.',
        'booking.errEndBeforeStart': 'Аяқталу күні басталу күнінен ерте болмауы керек.',
        'booking.errCountryRequired': 'Ел міндетті.',
        'booking.creating': 'Брондау жасалуда...',
        'booking.created': 'Брондау жасалды! Сіздің гидіңіз жақын арада хабарласады.',
        'booking.errCreateFailed': 'Брондауды жасау сәтсіз аяқталды. Қайта көріңіз.',
        'booking.errOnlyCompletedReview': 'Сіз тек аяқталған брондауға пікір қалдыра аласыз.',
        'booking.errReviewBookingNotFound': 'Пікір үшін брондау табылмады.',
        'booking.errSelectRating': 'Рейтингті таңдаңыз',
        'booking.reviewSubmitted': 'Пікіріңіз жіберілді. Рахмет!',
        'booking.errSubmitReview': 'Пікірді жіберу сәтсіз аяқталды.',
        'booking.serviceSchedule': 'Қызмет және кесте',
        'booking.selectServiceSchedule': 'Қызмет пен кестені таңдаңыз',
        'booking.country': 'Ел',
        'booking.city': 'Қала',
        'booking.startDate': 'Басталу күні',
        'booking.endDate': 'Аяқталу күні',
        'booking.checkAvailability': 'Қолжетімділікті тексеру',
        'booking.checking': 'Тексерілуде...',
        'booking.checkHint': 'Жалғастыру алдында қосымша тексеру',
        'booking.notesLabel': 'Гид үшін ескертпелер',
        'booking.requestBooking': 'Брондау сұрау',
        'booking.writeReview': 'Пікір жазу',
        'booking.rating': 'Рейтинг',
        'booking.commentOpt': 'Пікір (міндетті емес)',
        'booking.shareExperience': 'Тәжірибеңізбен бөлісіңіз…',
        'booking.sending': 'Жіберілуде…',
        'booking.submitReview': 'Пікірді жіберу',
        'booking.summary': 'Брондау қорытындысы',
        'booking.rate': 'Баға',
        'booking.perHour': 'сағат',
        'booking.perDay': 'күн',

        // Dashboard
        'dashboard.title': 'Менің басқару тақтасы',
        'dashboard.description': 'Брондауларыңызды, гидтерді және саяхат тәжірибелеріңізді басқарыңыз',
        'dashboard.upcomingBookings': 'Алдағы брондаулар',
        'dashboard.pastBookings': 'Өткен брондаулар',
        'dashboard.total': 'Барлығы',
        'dashboard.status': 'Күй',
        'dashboard.upcomingBookingsTitle': 'Алдағы брондаулар',
        'dashboard.noUpcoming': 'Алдағы брондаулар жоқ.',
        'dashboard.findGuide': 'Гид табу',
        'dashboard.planNext': 'және келесі саяхатыңызды жоспарлаңыз!',
        'dashboard.noPast': 'Өткен брондаулар жоқ',
        'dashboard.pageXofN': 'Бет {x} • Барлығы {n}',
        'dashboard.page': 'Бет {x}',
        'dashboard.myBookings': 'Менің брондауларым',
        'dashboard.profileInfo': 'Профиль ақпараты',
        'dashboard.refresh': 'Жаңарту',

        // Card actions
        'dashboard.cancel': 'Болдырмау',
        'dashboard.markComplete': 'Аяқталды',
        'dashboard.leaveReview': 'Пікір қалдыру',

        // Confirmations / statuses / errors
        'dashboard.confirmCancel': 'Осы брондауды болдырмау керек пе?',
        'dashboard.confirmComplete': 'Осы брондауды аяқталған деп белгілеу керек пе?',
        'dashboard.statusCancelled': 'Болдырылған',
        'dashboard.statusCompleted': 'Аяқталған',
        'dashboard.errCancel': 'Брондауды болдыру сәтсіз аяқталды',
        'dashboard.errComplete': 'Брондауды аяқтау сәтсіз аяқталды',
        'dashboard.errResolveProfile': 'Гид профилін анықтау мүмкін болмады',
        'dashboard.errResolveReview': 'Пікір мақсатын анықтау мүмкін болмады',

        // Profile section
        'dashboard.avatarHint': 'JPG, PNG, GIF, WEBP • Макс 5MB',
        'dashboard.uploading': 'Жүктелуде...',
        'dashboard.uploadPhoto': 'Фотосуретті жүктеу',
        'dashboard.removePhoto': 'Фотосуретті жою',
        'dashboard.firstName': 'Аты',
        'dashboard.lastName': 'Тегі',
        'dashboard.emailReadonly': 'Электрондық пошта (тек оқу)',
        'dashboard.phone': 'Телефон',
        'dashboard.saveChanges': 'Өзгерістерді сақтау',
        'dashboard.saving': 'Сақталуда…',
        'dashboard.saved': 'Профиль сақталды',
        'dashboard.errSave': 'Профильді сақтау сәтсіз аяқталды',
        'dashboard.avatarMax': 'Макс 5MB',
        'dashboard.avatarTypes': 'JPG/PNG/GIF/WEBP таңдаңыз',
        'dashboard.avatarUpdated': 'Аватар жаңартылды',
        'dashboard.errAvatarUpload': 'Аватарды жүктеу сәтсіз аяқталды',
        'dashboard.avatarRemoved': 'Аватар жойылды',
        'dashboard.errAvatarRemove': 'Аватарды жою сәтсіз аяқталды',

        // Overlays
        'dashboard.cancelling': 'Брондау болдырылуда…',
        'dashboard.completing': 'Брондау аяқталуда…',

        // Guide – nav/labels
        'guide.nav.overview': 'Шолу',
        'guide.nav.profileServices': 'Профиль және қызметтер',
        'guide.nav.analytics': 'Аналитика',

        'guide.common.yourName': 'Сіздің атыңыз',
        'guide.common.tourist': 'Турист',
        'guide.common.guest': 'Қонақ',
        'guide.common.service': 'Қызмет',
        'guide.common.scheduled': 'жоспарланған',

        // Overview
        'guide.overview.welcome': 'Қайта оралғаныңызға қуаныштымыз, {name}!',
        'guide.overview.todayCount': 'Бүгін {n} тур жоспарланған',
        'guide.overview.yourRating': 'Сіздің рейтингіңіз',
        'guide.overview.responseRate': 'Жауап беру деңгейі',
        'guide.overview.last30': 'Соңғы 30 күн',
        'guide.overview.todaySchedule': 'Бүгінгі кесте',
        'guide.overview.noToursToday': 'Бүгін турлар жоспарланбаған',

        // Bookings
        'guide.bookings.title': 'Брондауларды басқару',
        'guide.bookings.pending': 'Күтудегі сұраулар',
        'guide.bookings.confirmed': 'Расталған брондаулар',
        'guide.bookings.accept': 'Қабылдау',
        'guide.bookings.decline': 'Бас тарту',
        'guide.bookings.markCompleted': 'Аяқталған деп белгілеу',
        'guide.bookings.noPending': 'Күтудегі сұраулар жоқ',
        'guide.bookings.noConfirmed': 'Расталған брондаулар жоқ',
        'guide.bookings.offer': 'Ұсыныс',
        'guide.bookings.detailTitle': 'Брондау мәліметтері',
        'guide.bookings.status': 'Күй',
        'guide.bookings.tourist': 'Турист',
        'guide.bookings.dates': 'Күндер',
        'guide.bookings.location': 'Орын',
        'guide.bookings.message': 'Хабарлама',
        'guide.bookings.declineTitle': 'Сұрауды бас тарту',
        'guide.bookings.reasonOpt': 'Себеп (міндетті емес)',
        'guide.bookings.reasonPh': 'Мысалы, таңдалған күндерде бос емеспін',
        'guide.dashboard.bookingsRefreshed': 'Брондаулар жаңартылды',
        'guide.dashboard.acceptFailed': 'Брондауды қабылдау сәтсіз аяқталды',
        'guide.dashboard.declineFailed': 'Брондауды бас тарту сәтсіз аяқталды',
        'guide.dashboard.completeFailed': 'Аяқталған деп белгілеу сәтсіз аяқталды',

        // Profile
        'guide.dashboard.profileInfo': 'Профиль ақпараты',
        'guide.profile.firstName': 'Аты',
        'guide.profile.lastName': 'Тегі',
        'guide.profile.emailReadonly': 'Электрондық пошта (тек оқу)',
        'guide.profile.location': 'Орын (елдің атауы немесе коды)',
        'guide.profile.locationPh': 'мысалы, Өзбекстан немесе UZ',
        'guide.profile.bio': 'Биография',
        'guide.profile.bioPh': 'Өзіңіз және тәжірибеңіз туралы айтыңыз...',
        'guide.profile.languages': 'Тілдер (үтірмен бөлінген)',
        'guide.profile.languagesPh': 'мысалы, ағылшын, орыс, өзбек',
        'guide.profile.known': 'Белгілі',
        'guide.profile.langsNotLoaded': 'Тілдер каталогы жүктелмеді.',
        'guide.profile.years': 'Тәжірибе жылдары',

        // Portfolio/services
        'guide.service.item': 'Элемент',
        'guide.service.order': 'Рет: {n}',
        'guide.service.preview': 'Алдын ала қарау',
        'guide.service.noDesc': 'Сипаттама жоқ',
        'guide.service.empty': 'Портфолио бос',
        'guide.service.titlePh': 'мысалы, Ескі қалада серуен',
        'guide.service.descPh': 'Қысқа сипаттама…',
        'guide.service.orderLabel': 'Рет',
        'guide.service.imageReq': 'Сурет *',
        'guide.dashboard.portfolioCreated': 'Портфолио элементі жасалды',
        'guide.dashboard.portfolioCreateFailed': 'Портфолио жасау сәтсіз аяқталды',
        'guide.dashboard.confirmDelete': 'Бұл элементті жою керек пе?',
        'guide.dashboard.deleteFailed': 'Жою сәтсіз аяқталды',
        'guide.dashboard.portfolioMax': 'Макс 10MB',
        'guide.dashboard.photoRequired': 'Сурет қажет',

        // Photo / avatar
        'guide.dashboard.photoMax': 'Макс 5MB',
        'guide.dashboard.photoTypes': 'JPG/PNG/GIF таңдаңыз',
        'guide.dashboard.photoUpdated': 'Аватар жаңартылды',
        'guide.dashboard.photoUploadFailed': 'Аватарды жүктеу сәтсіз аяқталды',
        'guide.dashboard.photoRemoved': 'Аватар жойылды',
        'guide.dashboard.photoRemoveFailed': 'Аватарды жою сәтсіз аяқталды',

        // Earnings
        'guide.earn.thisMonth': 'Осы ай',
        'guide.earn.thisMonthShort': 'Осы ай',
        'guide.earn.totalBalance': 'Жалпы баланс',
        'guide.earn.monthly': 'Айлық табыс',
        'guide.earn.average': 'Орташа',
        'guide.earn.perBooking': 'Брондау үшін',
        'guide.earn.pendingShort': 'Күтуде',
        'guide.earn.available': 'Қолжетімді',
        'guide.earn.transactions': 'Транзакциялар тарихы',
        'guide.earn.export': 'Экспорт',
        'guide.earn.date': 'Күні',
        'guide.earn.tourist': 'Турист',
        'guide.earn.service': 'Қызмет',
        'guide.earn.amount': 'Сома',
        'guide.earn.status': 'Күй',
        'guide.earn.noTx': 'Транзакциялар жоқ',
        'guide.earn.withdraw': '${amount} шығару',

        // Reviews
        'guide.reviews.count': 'пікір',
        'guide.reviews.none': 'Әзірге пікірлер жоқ',

        // Stats / analytics
        'guide.stats.week': 'Осы аптадағы брондаулар',
        'guide.stats.month': 'Осы айдағы брондаулар',
        'guide.stats.completion': 'Аяқтау деңгейі',
        'guide.stats.response': 'Жауап беру деңгейі',
        'guide.stats.popular': 'Ең танымал қызметтер',
        'guide.stats.noData': 'Деректер жоқ',
        'guide.stats.monthlyPerf': 'Айлық өнімділік',
        'guide.stats.chartPlaceholder': 'Өнімділік аналитикасы графигі',

        // Common guide extras
        'guide.common.guestPlural': 'қонақтар',

        // Chat
        'chat.title': 'Хабарламалар',
        'chat.description': 'Гидтер мен туристермен әңгімелеріңіз',
        'chat.searchConversations': 'Әңгімелерде іздеу...',
        'chat.onlineNow': 'Қазір желіде',
        'chat.lastSeen': 'Соңғы рет көрілді',
        'chat.bookingDetails': 'Брондау мәліметтері',
        'chat.typeMessage': 'Хабарламаңызды теріңіз…',
        'chat.aiTranslation': 'Көптілді әңгімелер үшін AI аудармасы қолжетімді',
        'chat.photo': 'Фото',

        'chat.user': 'Пайдаланушы',
        'chat.me': 'Мен',
        'chat.errLoadMessages': 'Хабарламаларды жүктеу сәтсіз аяқталды',
        'chat.errSend': 'Хабарламаны жіберу сәтсіз аяқталды',
        'chat.noConversations': 'Әңгімелер жоқ',
        'chat.loadOlder': 'Ескі хабарламаларды жүктеу',
        'chat.selectConversation': 'Әңгіме таңдаңыз',
        'chat.more': 'Қосымша опциялар',
        'chat.back': 'Артқа',
        'chat.send': 'Жіберу',
        'chat.emojis': 'Эмодзилер',
        'chat.insertEmoji': 'Эмодзи қосу',
        'chat.rtcEnabled': 'Нақты уақыттағы чат қосылған.',

        // Auth
        'auth.welcomeBack': 'Қайта оралғаныңызға қуаныштымыз',
        'auth.createAccount': 'Есептік жазба жасаңыз',
        'auth.signInDescription': 'Жалғастыру үшін есептік жазбаңызға кіріңіз',
        'auth.signUpDescription': 'Бүкіл әлемдегі мыңдаған саяхатшылар мен гидтер қатарына қосылыңыз',
        'auth.joinAs': 'Мен мынадай болып қосылғым келеді:',
        'auth.tourist': 'Турист',
        'auth.touristDesc': 'Жергілікті гидтерді тауып, брондаңыз',
        'auth.guide': 'Гид',
        'auth.guideDesc': 'Жергілікті тәжірибеңізді ұсыныңыз',
        'auth.fullName': 'Толық аты',
        'auth.emailAddress': 'Электрондық пошта мекенжайы',
        'auth.yourLocation': 'Сіздің орналасқан жеріңіз',
        'auth.password': 'Құпия сөз',
        'auth.confirmPassword': 'Құпия сөзді растау',
        'auth.agreeTerms': 'Мен келісемін',
        'auth.termsOfService': 'Қызмет көрсету шарттары',
        'auth.privacyPolicy': 'Құпиялылық саясаты',
        'auth.signIn': 'Кіру',
        'auth.noAccount': 'Есептік жазбаңыз жоқ па?',
        'auth.haveAccount': 'Есептік жазбаңыз бар ма?',
        'auth.signUp': 'Тіркелу',
        'auth.continueWith': 'Немесе жалғастырыңыз',
        'auth.google': 'Google',
        'auth.facebook': 'Facebook',
        'auth.trustedBy': 'Бүкіл әлемдегі мыңдаған саяхатшылар сенеді',
        'auth.secureVerified': 'Қауіпсіз және расталған',
        'auth.safe': '100% қауіпсіз',

        // Footer
        'footer.description': 'Бүкіл әлем бойынша расталған жергілікті гидтермен байланысыңыз. Шынайы тәжірибелерді ашыңыз және ұмытылмас естеліктер жасаңыз.',
        'footer.quickLinks': 'Жылдам сілтемелер',
        'footer.findGuides': 'Гидтерді табу',
        'footer.becomeGuide': 'Гид болу',
        'footer.aboutUs': 'Біз туралы',
        'footer.howItWorks': 'Бұл қалай жұмыс істейді',
        'footer.safety': 'Қауіпсіздік',
        'footer.support': 'Қолдау',
        'footer.helpCenter': 'Көмек орталығы',
        'footer.contactUs': 'Бізбен байланысыңыз',
        'footer.termsOfService': 'Қызмет көрсету шарттары',
        'footer.privacyPolicy': 'Құпиялылық саясаты',
        'footer.cancellationPolicy': 'Болдырмау саясаты',
        'footer.contact': 'Байланыс',
        'footer.newsletter': 'Ақпараттық бюллетень',
        'footer.yourEmail': 'Сіздің электрондық поштаңыз',
        'footer.subscribe': 'Жазылу',
        'footer.allRightsReserved': 'Барлық құқықтар қорғалған.',
        'footer.sitemap': 'Сайт картасы',
        'footer.accessibility': 'Қолжетімділік',
        'footer.cookiePolicy': 'Cookie саясаты',

        // Common
        'common.loading': 'Жүктелуде...',
        'common.error': 'Қате',
        'common.success': 'Сәтті',
        'common.cancel': 'Болдырмау',
        'common.save': 'Сақтау',
        'common.edit': 'Өңдеу',
        'common.delete': 'Жою',
        'common.view': 'Қарау',
        'common.close': 'Жабу',
        'common.next': 'Келесі',
        'common.previous': 'Алдыңғы',
        'common.search': 'Іздеу',
        'common.filter': 'Сүзгі',
        'common.sort': 'Сұрыптау',
        'common.date': 'Күні',
        'common.time': 'Уақыт',
        'common.location': 'Орын',
        'common.price': 'Баға',
        'common.rating': 'Рейтинг',
        'common.reviews': 'Пікірлер',
        'common.hour': 'сағат',
        'common.hours': 'сағаттар',
        'common.min': 'Мин',
        'common.max': 'Макс',
        'common.all': 'Барлығы',
        'common.none': 'Ешқандай',
        'common.yes': 'Иә',
        'common.no': 'Жоқ',
        'common.ok': 'ОК',
    },
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const saved = localStorage.getItem('language');
        return ['en', 'uz', 'ru', 'kz'].includes(saved) ? saved : 'en';
    });

    const t = (key) => {
        return (translations[language] && translations[language][key])
            || (translations.en && translations.en[key])
            || key;
    };

    useEffect(() => {
        localStorage.setItem('language', language);
        document.documentElement.setAttribute('lang', language);
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
