server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # 🔧 Media files (avatars, uploads va hokazo)
    location /media/ {
        alias /app/media/;
        autoindex off;
    }
}
