# Generated by Django 5.2.4 on 2025-08-27 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 code (e.g., UZ, US)",
                        max_length=2,
                        unique=True,
                        verbose_name="Country code",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Country name")),
                (
                    "flag",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Flag emoji"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="common_coun_code_14bc84_idx"),
                    models.Index(
                        fields=["is_active"], name="common_coun_is_acti_b7dba7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 639-1 code (e.g., en, ru)",
                        max_length=5,
                        unique=True,
                        verbose_name="Language code",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Language name")),
                (
                    "native_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Native name"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="common_lang_code_4aafad_idx"),
                    models.Index(
                        fields=["is_active"], name="common_lang_is_acti_ae1234_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Service type"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icon class/name"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Service type",
                "verbose_name_plural": "Service types",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="common_serv_is_acti_ae37fa_idx"
                    ),
                    models.Index(fields=["order"], name="common_serv_order_642e08_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="City name")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="common.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["country", "name"],
                        name="common_city_country_002aef_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="common_city_is_acti_21b47a_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "name"), name="uniq_city_name_per_country"
                    )
                ],
            },
        ),
    ]
