# Generated by Django 5.2.4 on 2025-10-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Country name"
            ),
        ),
    ]
