# Generated by Django 5.2.4 on 2025-07-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="city",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                help_text="ISO 3166-1 alpha-2 code (e.g., UZ, US)",
                max_length=2,
                unique=True,
                verbose_name="Country code",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(
                help_text="ISO 639-1 code (e.g., en, ru)",
                max_length=5,
                unique=True,
                verbose_name="Language code",
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["country", "name"], name="common_city_country_002aef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["is_active"], name="common_city_is_acti_21b47a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(fields=["code"], name="common_coun_code_14bc84_idx"),
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(
                fields=["is_active"], name="common_coun_is_acti_b7dba7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="language",
            index=models.Index(fields=["code"], name="common_lang_code_4aafad_idx"),
        ),
        migrations.AddIndex(
            model_name="language",
            index=models.Index(
                fields=["is_active"], name="common_lang_is_acti_ae1234_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicetype",
            index=models.Index(
                fields=["is_active"], name="common_serv_is_acti_ae37fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicetype",
            index=models.Index(fields=["order"], name="common_serv_order_642e08_idx"),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                fields=("country", "name"), name="uniq_city_name_per_country"
            ),
        ),
    ]
