# Generated by Django 5.2.4 on 2025-10-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_country_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(
                help_text="ISO 639-1 code (e.g., en, ru)",
                max_length=30,
                unique=True,
                verbose_name="Language code",
            ),
        ),
    ]
