# Generated by Django 5.2.4 on 2025-07-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_delete_emailverification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoginAttempt",
        ),
        migrations.RemoveField(
            model_name="user",
            name="apple_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="facebook_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="google_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AddField(
            model_name="user",
            name="country_name",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Country name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=301, verbose_name="Full name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Max file size: 5MB",
                null=True,
                upload_to="avatars/%Y/%m/",
                verbose_name="Avatar",
            ),
        ),
    ]
