# Generated by Django 5.2.4 on 2025-08-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_delete_loginattempt_remove_user_apple_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("customer", "Customer"),
                    ("admin", "Admin"),
                    ("superadmin", "Superadmin"),
                ],
                default="client",
                max_length=20,
                verbose_name="User role",
            ),
        ),
    ]
