server {
    listen 80;
    server_name uzguide.com www.uzguide.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name uzguide.com www.uzguide.com;

    ssl_certificate /etc/letsencrypt/live/uzguide.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/uzguide.com/privkey.pem;

    # max upload size
    client_max_body_size 20M;

    location /django-static/ {
        alias /app/staticfiles/;
        add_header Cache-Control "public, max-age=3600";
        access_log off;
    }

    location /media/ {
        alias /app/media;
        add_header Cache-Control "public, max-age=3600";
        access_log off;
    }

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 60s;
        proxy_read_timeout 120s;
    }
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 60s;
        proxy_read_timeout 120s;
    }
}