# Generated by Django 5.2.4 on 2025-08-04 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initiator",
                    models.CharField(
                        choices=[("client", "Client"), ("guide", "Guide")],
                        help_text="Who initiated the dispute",
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for the dispute")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "resolution_details",
                    models.TextField(blank=True, help_text="Details of the resolution"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the dispute was resolved", null=True
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="bookings.booking",
                    ),
                ),
                (
                    "chat_room",
                    models.OneToOneField(
                        blank=True,
                        help_text="Chat room for dispute communication",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispute",
                        to="chat.chatroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute",
                "verbose_name_plural": "Disputes",
                "db_table": "disputes",
            },
        ),
    ]
