# Generated by Django 5.2.4 on 2025-07-15 12:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "dispute_type",
                    models.CharField(
                        choices=[
                            ("service_quality", "Service Quality"),
                            ("no_show", "No Show"),
                            ("payment_issue", "Payment Issue"),
                            ("cancellation", "Cancellation Issue"),
                            ("communication", "Communication Problem"),
                            ("safety", "Safety Concern"),
                            ("fraud", "Suspected Fraud"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Dispute type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under Review"),
                            ("awaiting_response", "Awaiting Response"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("escalated", "Escalated"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Assigned at"
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("client", "In favor of client"),
                            ("provider", "In favor of provider"),
                            ("mutual", "Mutual agreement"),
                            ("no_action", "No action required"),
                            ("refund", "Refund issued"),
                            ("warning", "Warning issued"),
                            ("suspended", "Account suspended"),
                        ],
                        max_length=20,
                        verbose_name="Resolution",
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Resolution notes"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved at"
                    ),
                ),
                (
                    "response_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Response deadline"
                    ),
                ),
                (
                    "resolution_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolution deadline"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute",
                "verbose_name_plural": "Disputes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("status_changed", "Status Changed"),
                            ("assigned", "Assigned"),
                            ("evidence_added", "Evidence Added"),
                            ("message_sent", "Message Sent"),
                            ("escalated", "Escalated"),
                            ("resolved", "Resolved"),
                            ("reopened", "Reopened"),
                            ("warning_issued", "Warning Issued"),
                            ("account_action", "Account Action Taken"),
                        ],
                        max_length=30,
                        verbose_name="Action type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "old_value",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Old value"
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="New value"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute action",
                "verbose_name_plural": "Dispute actions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("screenshot", "Screenshot"),
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("chat_log", "Chat Log"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Evidence type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="disputes/evidence/%Y/%m/", verbose_name="File"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="File size (bytes)"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is verified"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute evidence",
                "verbose_name_plural": "Dispute evidence",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Only visible to admins",
                        verbose_name="Internal note",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute message",
                "verbose_name_plural": "Dispute messages",
                "ordering": ["created_at"],
            },
        ),
    ]
