# Generated by Django 5.2.4 on 2025-07-15 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_initial"),
        ("disputes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["admin", "superadmin"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_disputes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned to",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disputes",
                to="bookings.booking",
                verbose_name="Related booking",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reported_disputes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reporter",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_disputes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Resolved by",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="respondent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_disputes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Respondent",
            ),
        ),
        migrations.AddField(
            model_name="disputeaction",
            name="dispute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="disputes.dispute",
                verbose_name="Dispute",
            ),
        ),
        migrations.AddField(
            model_name="disputeaction",
            name="performed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispute_actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Performed by",
            ),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="dispute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="disputes.dispute",
                verbose_name="Dispute",
            ),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_evidence",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Submitted by",
            ),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_evidence",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Verified by",
            ),
        ),
        migrations.AddField(
            model_name="disputemessage",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                related_name="messages",
                to="disputes.disputeevidence",
                verbose_name="Attachments",
            ),
        ),
        migrations.AddField(
            model_name="disputemessage",
            name="dispute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="disputes.dispute",
                verbose_name="Dispute",
            ),
        ),
        migrations.AddField(
            model_name="disputemessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispute_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender",
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["status", "priority", "-created_at"],
                name="disputes_di_status_703f59_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["reporter", "status"], name="disputes_di_reporte_fae112_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["respondent", "status"], name="disputes_di_respond_c1ad75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["assigned_to", "status"], name="disputes_di_assigne_eb5d18_idx"
            ),
        ),
    ]
