# Generated by Django 5.2.4 on 2025-08-04 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("disputes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disputes_as_client",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="guide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disputes_as_guide",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolver",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who resolved the dispute",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["booking"], name="disputes_booking_2aad4d_idx"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["client"], name="disputes_client__4887ab_idx"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["guide"], name="disputes_guide_i_87a3f0_idx"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["status"], name="disputes_status_811094_idx"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["resolved_at"], name="disputes_resolve_9bb9f0_idx"
            ),
        ),
    ]
