# Generated by Django 5.2.4 on 2025-08-26 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("chat", "0001_initial"),
        ("common", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="client_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="profiles.clientprofile",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="conversation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking",
                to="chat.conversation",
                verbose_name="Conversation",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="customer_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="profiles.customerprofile",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="service_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.servicetype",
                verbose_name="Service type",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["customer_profile", "status"],
                name="bookings_bo_custome_3bc957_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["start_date", "end_date"], name="bookings_bo_start_d_8ecf7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "created_at"], name="bookings_bo_status_72dd85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["country", "city"], name="bookings_bo_country_66afe7_idx"
            ),
        ),
    ]
