# Generated by Django 5.2.4 on 2025-08-04 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings_as_client",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="guide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings_as_guide",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.service",
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="original_request",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_requests_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="guide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_requests_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="requested_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.service",
            ),
        ),
        migrations.AddField(
            model_name="bookingupdate",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="bookingupdate",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["client", "status"], name="bookings_client__43bbe1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["guide", "status"], name="bookings_guide_i_ce36e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["start_date"], name="bookings_start_d_94c02c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="bookings_status_51373b_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingrequest",
            index=models.Index(
                fields=["guide", "status"], name="booking_req_guide_i_8d6c51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingrequest",
            index=models.Index(
                fields=["client", "status"], name="booking_req_client__443adb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingrequest",
            index=models.Index(
                fields=["requested_date"], name="booking_req_request_e0f77d_idx"
            ),
        ),
    ]
