# Generated by Django 5.2.4 on 2025-09-09 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking",
                to="chat.conversation",
                verbose_name="Conversation",
            ),
        ),
    ]
