# Generated by Django 5.2.4 on 2025-08-26 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
        ("common", "0001_initial"),
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="booking",
            name="bookings_bo_custome_3bc957_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="bookings_bo_start_d_8ecf7f_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="bookings_bo_status_72dd85_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="bookings_bo_country_66afe7_idx",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="conversation",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="longitude",
        ),
        migrations.AddField(
            model_name="booking",
            name="cancelled_by_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="conversation_id",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Conversation ID"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="accepted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="booking",
            name="duration_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_date",
            field=models.DateField(db_index=True, verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="location",
            field=models.CharField(blank=True, max_length=255, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="number_of_people",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="rate_type",
            field=models.CharField(
                blank=True,
                choices=[("hourly", "Hourly"), ("daily", "Daily"), ("fixed", "Fixed")],
                default="daily",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="special_requirements",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_date",
            field=models.DateField(db_index=True, verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("updated", "Updated"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Title"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["customer_profile", "status", "-created_at"],
                name="bookings_bo_custome_94b628_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["start_date", "end_date", "status"],
                name="bookings_bo_start_d_151a4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["country", "city", "status"],
                name="bookings_bo_country_b0fab2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["conversation_id", "status"],
                name="bookings_bo_convers_7c5dd7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="booking_end_date_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("number_of_people__gt", 0)),
                name="booking_positive_people_count",
            ),
        ),
    ]
