# Generated by Django 5.2.4 on 2025-09-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancellation_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cancellation reason"
            ),
        ),
    ]
