# Generated by Django 5.2.4 on 2025-08-22 19:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="helpful_count",
        ),
        migrations.AddField(
            model_name="review",
            name="dislike_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Dislike count"),
        ),
        migrations.AddField(
            model_name="review",
            name="like_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Like count"),
        ),
        migrations.AlterField(
            model_name="review",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Client (author of review)",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="communication_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Communication rating",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="overall_rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Overall rating",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="punctuality_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Punctuality rating",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="service_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Service quality rating",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="value_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Value for money rating",
            ),
        ),
        migrations.CreateModel(
            name="ReviewReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[("like", "Like"), ("dislike", "Dislike")],
                        max_length=10,
                        verbose_name="Reaction type",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, verbose_name="Optional comment (reason or feedback)"
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="reviews.review",
                        verbose_name="Review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review reaction",
                "verbose_name_plural": "Review reactions",
            },
        ),
        migrations.DeleteModel(
            name="ReviewHelpful",
        ),
        migrations.AddIndex(
            model_name="reviewreaction",
            index=models.Index(
                fields=["review", "reaction_type"],
                name="reviews_rev_review__de72b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewreaction",
            index=models.Index(
                fields=["user", "reaction_type"], name="reviews_rev_user_id_d1f48a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewreaction",
            unique_together={("review", "user")},
        ),
    ]
