# Generated by Django 5.2.4 on 2025-08-21 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "to_email",
                    models.EmailField(max_length=254, verbose_name="To email"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("body_text", models.TextField(blank=True, verbose_name="Body text")),
                ("body_html", models.TextField(blank=True, verbose_name="Body HTML")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent at"),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Email provider"
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Provider message ID"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error message"),
                ),
            ],
            options={
                "verbose_name": "Email log",
                "verbose_name_plural": "Email logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Object ID"),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Action URL"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Is read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read at"),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Extra data"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Type code"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Type name")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("booking", "Booking"),
                            ("chat", "Chat"),
                            ("review", "Review"),
                            ("system", "System"),
                            ("account", "Account"),
                            ("dispute", "Dispute"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "email_template",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Email template name"
                    ),
                ),
                (
                    "push_template",
                    models.TextField(
                        blank=True, verbose_name="Push notification template"
                    ),
                ),
                (
                    "is_email_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Email enabled by default"
                    ),
                ),
                (
                    "is_push_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Push enabled by default"
                    ),
                ),
                (
                    "is_in_app_enabled",
                    models.BooleanField(
                        default=True, verbose_name="In-app enabled by default"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification type",
                "verbose_name_plural": "Notification types",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Email notifications enabled"
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Push notifications enabled"
                    ),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(
                        default=True, verbose_name="In-app notifications enabled"
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Quiet hours enabled"
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Quiet hours start"
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Quiet hours end"
                    ),
                ),
                (
                    "chat_message_email",
                    models.BooleanField(
                        default=False, verbose_name="Email for chat messages"
                    ),
                ),
                (
                    "chat_message_push",
                    models.BooleanField(
                        default=True, verbose_name="Push for chat messages"
                    ),
                ),
            ],
            options={
                "verbose_name": "User notification settings",
                "verbose_name_plural": "User notification settings",
            },
        ),
        migrations.CreateModel(
            name="UserNotificationTypeSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="Email enabled"),
                ),
                (
                    "push_enabled",
                    models.BooleanField(default=True, verbose_name="Push enabled"),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(default=True, verbose_name="In-app enabled"),
                ),
            ],
            options={
                "verbose_name": "User notification type setting",
                "verbose_name_plural": "User notification type settings",
            },
        ),
    ]
