# Generated by Django 5.2.4 on 2025-07-15 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text message"),
                            ("image", "Image"),
                            ("file", "File"),
                            ("location", "Location"),
                            ("system", "System message"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Message type",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Text content")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="JPEG, PNG, max 10MB",
                        null=True,
                        upload_to="chat/images/%Y/%m/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="PDF, DOC, DOCX, max 25MB",
                        null=True,
                        upload_to="chat/files/%Y/%m/",
                        verbose_name="File",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Original file name"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="File size (bytes)"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Location name"
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="Is edited"),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Edited at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageRead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "read_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Read at"),
                ),
            ],
            options={
                "verbose_name": "Message read receipt",
                "verbose_name_plural": "Message read receipts",
            },
        ),
        migrations.CreateModel(
            name="UserTypingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_typing",
                    models.BooleanField(default=False, verbose_name="Is typing"),
                ),
                (
                    "last_typed_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last typed at"),
                ),
            ],
            options={
                "verbose_name": "User typing status",
                "verbose_name_plural": "User typing statuses",
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct message"),
                            ("booking", "Booking related"),
                            ("support", "Support chat"),
                        ],
                        default="direct",
                        max_length=20,
                        verbose_name="Room type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_room",
                        to="bookings.booking",
                        verbose_name="Related booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat room",
                "verbose_name_plural": "Chat rooms",
                "ordering": ["-updated_at"],
            },
        ),
    ]
