# Generated by Django 5.2.4 on 2025-08-29 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blockeduser",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="conversation",
            name="chat_conver_updated_1f6ffe_idx",
        ),
        migrations.RemoveIndex(
            model_name="conversation",
            name="chat_conver_user1_i_5511b6_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="chat_messag_convers_d0740f_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="chat_messag_sender__7ea760_idx",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="last_activity",
        ),
        migrations.AlterField(
            model_name="blockeduser",
            name="blocked",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_by_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blockeduser",
            name="blocker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blockeduser",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="deleted_for",
            field=models.CharField(
                choices=[("none", "None"), ("sender", "Sender"), ("both", "Both")],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("file", "File"),
                    ("system", "System"),
                    ("booking", "Booking"),
                ],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
