# Generated by Django 5.2.4 on 2025-07-19 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messageread",
            options={
                "verbose_name": "Read receipt",
                "verbose_name_plural": "Read receipts",
            },
        ),
        migrations.AlterModelOptions(
            name="usertypingstatus",
            options={},
        ),
        migrations.AlterField(
            model_name="message",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="chat/files/%Y/%m/",
                verbose_name="File / media",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="chat/images/%Y/%m/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="location_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("file", "File (doc/zip)"),
                    ("audio", "Audio / voice"),
                    ("video", "Video"),
                    ("location", "Location"),
                    ("system", "System"),
                ],
                default="text",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="chat.message",
                verbose_name="Reply to",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="messageread",
            name="read_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="usertypingstatus",
            name="is_typing",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usertypingstatus",
            name="last_typed_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="usertypingstatus",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="typing_statuses",
                to="chat.chatroom",
            ),
        ),
        migrations.AlterField(
            model_name="usertypingstatus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="typing_statuses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
