# Generated by Django 5.2.4 on 2025-07-22 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
        ("chat", "0003_alter_messageread_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatroom",
            options={
                "ordering": ["-last_activity_at", "-updated_at"],
                "verbose_name": "Chat room",
                "verbose_name_plural": "Chat rooms",
            },
        ),
        migrations.AddField(
            model_name="chatroom",
            name="last_activity_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last activity"),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="last_message_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last message time"
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="last_message_preview",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Last message preview"
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="last_message_sender_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="Last message sender ID"
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="last_message_type",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Last message type"
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="total_messages",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total messages count"
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="unread_counts",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Unread counts per user"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="read_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Read count"),
        ),
        migrations.AddField(
            model_name="message",
            name="replies_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Replies count"),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["last_activity_at"], name="chat_chatro_last_ac_c272a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["is_active", "last_message_at"],
                name="chat_chatro_is_acti_04c18b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "is_deleted", "created_at"],
                name="chat_messag_room_id_dcc9c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["reply_to", "created_at"], name="chat_messag_reply_t_5715b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageread",
            index=models.Index(
                fields=["message", "read_at"], name="chat_messag_message_72c1ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageread",
            index=models.Index(
                fields=["user", "message"], name="chat_messag_user_id_f12ddc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertypingstatus",
            index=models.Index(
                fields=["room", "is_typing"], name="chat_userty_room_id_85167f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertypingstatus",
            index=models.Index(
                fields=["user", "last_typed_at"], name="chat_userty_user_id_abb0d6_idx"
            ),
        ),
    ]
