# Generated by Django 5.2.4 on 2025-08-29 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_blockeduser_options_alter_conversation_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blockeduser",
            options={
                "verbose_name": "Blocked User",
                "verbose_name_plural": "Blocked Users",
            },
        ),
        migrations.AlterModelOptions(
            name="conversation",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blockeduser",
            name="blocked",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blockeduser",
            name="blocker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocking",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blockeduser",
            name="reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="message",
            name="deleted_for",
            field=models.CharField(
                choices=[
                    ("none", "Not Deleted"),
                    ("sender", "Deleted by Sender"),
                    ("both", "Deleted by Both"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Message"),
                    ("booking", "Booking Update"),
                    ("system", "System Message"),
                ],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["-updated_at"], name="chat_conver_updated_1f6ffe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user1", "user2"], name="chat_conver_user1_i_5511b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "-created_at"],
                name="chat_messag_convers_d0740f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "is_read"], name="chat_messag_sender__7ea760_idx"
            ),
        ),
    ]
